/**
 * Merchant Library v2 (backlog #47) - wired into the live app (imported and spread
 * into App.jsx's MERCHANT_LIBRARY array).
 *
 * Source: being_wealthy_merchant_library_expanded_v2.xlsx (171 entries, project file),
 * converted mechanically, then annotated with the identity/classification confidence
 * split and Merchant Type field designed in INFERENCE_ENGINE_DESIGN.md §12. Verified
 * against v1 of this workbook before adoption: zero removals, 11 genuinely new
 * merchants, and every other change to an existing row was strictly additive (more
 * bank-text patterns, richer legal-entity notes) - a clean superset, not a rewrite.
 * Verified against the CURRENT live MERCHANT_LIBRARY in App.jsx: zero pattern
 * conflicts.
 *
 * Field meanings:
 * - identityConfidence: how sure we are this pattern really identifies the named
 *   merchant. Defaults "High" throughout - the source file's stated scope is
 *   well-known, unambiguous national brands matched by exact bank/UPI text.
 * - classificationConfidence: how sure we are the suggested category/sub is right.
 *   This is what the source spreadsheet's single "Confidence" column actually meant
 *   (its own Notes describe classification ambiguity - e.g. "Decathlon as fitness
 *   vs. general shopping" - never identity ambiguity).
 * - category === null is a DELIBERATE signal: identity is known, classification is
 *   intentionally withheld. Two different reasons produce this:
 *   (a) The source file's own original 3 rows (LIC, general Amazon shopping,
 *       Policybazaar) - the true category depends on the specific transaction, not
 *       the brand.
 *   (b) FOUR ENTRIES OVERRIDDEN HERE, against the source spreadsheet's own suggested
 *       category, on review before adoption:
 *         - Razorpay, PhonePe -> merchantType "Payment Aggregator". The source
 *           spreadsheet suggested a plain Expense/Transfer category for these, but a
 *           payment aggregator or UPI rail's name on a bank statement usually means
 *           money passed THROUGH it to an unrelated real merchant, not that money was
 *           spent "at Razorpay" or "at PhonePe" specifically. Accepting the source's
 *           suggested category here would silently misclassify a potentially large
 *           number of unrelated transactions that merely happen to route through
 *           these rails - exactly the failure mode the processor-detection layer in
 *           INFERENCE_ENGINE_DESIGN.md §12 exists to prevent. No per-transaction
 *           merchant-extraction step exists yet to recover the real merchant behind
 *           the rail, so honesty requires withholding a category rather than guessing
 *           one, same as the other null-category rows.
 *         - Fi Money / EpiFi, Jupiter Money -> merchantType "Financial Institution".
 *           The source spreadsheet suggested Expense/Personal/Fintech, but these
 *           neobank apps are commonly used as a second linked bank account - money
 *           moving to them is frequently a SELF-TRANSFER, not spending. This is the
 *           same structural ambiguity the source file itself already recognized for
 *           LIC (could be a pure expense or an investment-oriented product);
 *           extended here to a case the source spreadsheet had not itself flagged.
 *   Every overridden entry carries a note recording the source's original suggestion,
 *   for anyone who wants to review the override itself.
 * - merchantType: "Investment Platform" for Investment-category rows, "Payment
 *   Aggregator" / "Financial Institution" for the four overrides above, "Merchant"
 *   otherwise.
 * - groupType is "category" wherever the source sets one at all - it deliberately
 *   never recommends "sameCommitment" for any row (see the source workbook's own
 *   Methodology sheet: that grouping can only be discovered from a specific person's
 *   own inconsistent bank text, never predicted generically in advance).
 *
 * NOT included, on purpose: Frequency, Control, Amount Behaviour, Linked Account -
 * these are judgments about a specific person's own behaviour and intent, or facts
 * the app already computes from real observed transaction history.
 *
 * Snabbit's classification (Expense/Household/Grocery, High confidence, described in
 * its own notes as "home services / quick delivery") reads as a plausible but
 * debatable stretch and was NOT independently verifiable - left as the source
 * provided it, flagged here rather than silently passed through, worth a human
 * glance rather than an override.
 */
export const MERCHANT_LIBRARY_V2 = [
  { merchant: "Zerodha", patterns: ["ZERODHA", "ZERODHA BROKING", "RAINMATTER"], merchantType: "Investment Platform", category: "Investment", sub: null, group: "Equities & Brokerage", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Discount broker - SIP/lumpsum/redemption via linked bank debit or Coin. Legal Entity: Zerodha Broking Limited / Rainmatter." },
  { merchant: "Groww", patterns: ["GROWW", "NEXTBILLION TECHNOLOGY"], merchantType: "Investment Platform", category: "Investment", sub: null, group: "Equities & Brokerage", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Legal Entity: Nextbillion Technology Private Limited." },
  { merchant: "Upstox", patterns: ["UPSTOX", "RKSV SECURITIES"], merchantType: "Investment Platform", category: "Investment", sub: null, group: "Equities & Brokerage", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Angel One", patterns: ["ANGEL ONE", "ANGEL BROKING"], merchantType: "Investment Platform", category: "Investment", sub: null, group: "Equities & Brokerage", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "ICICI Direct", patterns: ["ICICIDIRECT", "ICICI SECURITIES"], merchantType: "Investment Platform", category: "Investment", sub: null, group: "Equities & Brokerage", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "HDFC Securities", patterns: ["HDFC SECURITIES", "HDFCSEC"], merchantType: "Investment Platform", category: "Investment", sub: null, group: "Equities & Brokerage", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Kotak Securities", patterns: ["KOTAK SECURITIES", "KSTOCK"], merchantType: "Investment Platform", category: "Investment", sub: null, group: "Equities & Brokerage", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "5paisa", patterns: ["5PAISA", "5PAISA CAPITAL"], merchantType: "Investment Platform", category: "Investment", sub: null, group: "Equities & Brokerage", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Paytm Money", patterns: ["PAYTM MONEY", "ONE97", "ONE 97 COMMUNICATIONS"], merchantType: "Investment Platform", category: "Investment", sub: null, group: "Equities & Brokerage", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Distinct from Paytm's own wallet/UPI rails - broking arm specifically. Legal Entity: One97 Communications Limited." },
  { merchant: "Zerodha Coin", patterns: ["COIN BY ZERODHA", "ZERODHA COIN"], merchantType: "Investment Platform", category: "Investment", sub: null, group: "Mutual Funds", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Zerodha's direct mutual fund platform - kept separate from equity brokerage above." },
  { merchant: "HDFC Mutual Fund", patterns: ["HDFC MUTUAL FUND", "HDFC AMC"], merchantType: "Investment Platform", category: "Investment", sub: null, group: "Mutual Funds", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Direct AMC-side SIP debit, as opposed to via a broker/aggregator above." },
  { merchant: "SBI Mutual Fund", patterns: ["SBI MUTUAL FUND", "SBI FUNDS MGMT"], merchantType: "Investment Platform", category: "Investment", sub: null, group: "Mutual Funds", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "ICICI Prudential Mutual Fund", patterns: ["ICICI PRUDENTIAL AMC", "ICICI PRU MF"], merchantType: "Investment Platform", category: "Investment", sub: null, group: "Mutual Funds", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Axis Mutual Fund", patterns: ["AXIS MUTUAL FUND", "AXIS AMC"], merchantType: "Investment Platform", category: "Investment", sub: null, group: "Mutual Funds", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Nippon India Mutual Fund", patterns: ["NIPPON INDIA MF", "RELIANCE MUTUAL FUND"], merchantType: "Investment Platform", category: "Investment", sub: null, group: "Mutual Funds", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Formerly Reliance Mutual Fund - both name forms still appear in older statements." },
  { merchant: "Kotak Mutual Fund", patterns: ["KOTAK MUTUAL FUND", "KOTAK MF"], merchantType: "Investment Platform", category: "Investment", sub: null, group: "Mutual Funds", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "UTI Mutual Fund", patterns: ["UTI MUTUAL FUND", "UTI AMC"], merchantType: "Investment Platform", category: "Investment", sub: null, group: "Mutual Funds", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "NPS (National Pension System)", patterns: ["NPS", "NSDL NPS", "PROTEAN NPS", "CRA NPS"], merchantType: "Investment Platform", category: "Investment", sub: null, group: null, groupType: null, identityConfidence: "High", classificationConfidence: "High", notes: "Frequency/cadence is already handled specially in the app's own NPS logic - no merchant group needed." },
  { merchant: "Paytm Gold / Digital Gold", patterns: ["PAYTM GOLD", "PHONEPE GOLD", "SAFEGOLD", "MMTC PAMP"], merchantType: "Investment Platform", category: "Investment", sub: null, group: "Digital Gold", groupType: "category", identityConfidence: "High", classificationConfidence: "Medium", notes: "Small, frequent digital gold purchases are common via multiple apps - genuinely different vendors, one purpose." },
  { merchant: "LIC", patterns: ["LIC", "LIFE INSURANCE CORP"], merchantType: "Merchant", category: null, sub: null, group: null, groupType: null, identityConfidence: "High", classificationConfidence: "Insufficient", notes: "Deliberately left blank - could be an investment-oriented policy (endowment/ULIP) or a pure protection premium (Expense). Needs the person's own knowledge of their specific policy - see Methodology." },
  { merchant: "BigBasket", patterns: ["BIGBASKET", "BB INSTANT", "SUPERMARKET GROCERY"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Grocery", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "DMart / D-Mart Ready", patterns: ["DMART", "AVENUE SUPERMART", "D MART READY"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Grocery", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Zepto", patterns: ["ZEPTO", "ZEPTOMARKETPLACE", "KIRANAKART"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Grocery", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Legal Entity: Kiranakart Technologies / Zepto Private Limited." },
  { merchant: "Blinkit", patterns: ["BLINKIT", "BLINK COMMERCE", "GROFERS"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Grocery", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Formerly Grofers - both name forms may appear. Legal Entity: Blink Commerce Private Limited (formerly Grofers)." },
  { merchant: "Swiggy Instamart", patterns: ["SWIGGY INSTAMART", "INSTAMART", "BUNDL TECHNOLOGIES"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Grocery", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Distinct from plain 'Swiggy' below, which is food delivery, not grocery. Legal Entity: Swiggy Limited (formerly Bundl Technologies)." },
  { merchant: "JioMart", patterns: ["JIOMART", "RELIANCE JIOMART"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Grocery", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Nature's Basket", patterns: ["NATURES BASKET"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Grocery", groupType: "category", identityConfidence: "High", classificationConfidence: "Medium" },
  { merchant: "Reliance Fresh / Reliance Smart", patterns: ["RELIANCE FRESH", "RELIANCE SMART", "RELIANCE RETAIL"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Grocery", groupType: "category", identityConfidence: "High", classificationConfidence: "Medium" },
  { merchant: "Spencer's Retail", patterns: ["SPENCERS RETAIL", "SPENCER'S"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Grocery", groupType: "category", identityConfidence: "High", classificationConfidence: "Medium" },
  { merchant: "More Retail", patterns: ["MORE RETAIL", "MORE SUPERMARKET"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Grocery", groupType: "category", identityConfidence: "High", classificationConfidence: "Medium" },
  { merchant: "Star Bazaar", patterns: ["STAR BAZAAR", "TATA STARQUIK"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Grocery", groupType: "category", identityConfidence: "High", classificationConfidence: "Medium" },
  { merchant: "Local/regional grocery, kirana, hypermarket", patterns: ["(varies widely - see Notes)"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Grocery", groupType: "category", identityConfidence: "High", classificationConfidence: "Low", notes: "Cannot be pre-populated by name - this is exactly the gap the person's own 'suggested clusters' / manual grouping already covers well for local vendors." },
  { merchant: "Electricity - BESCOM (Bangalore)", patterns: ["BESCOM", "BANGALORE ELECTRICITY"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Electricity", groupType: "category", identityConfidence: "High", classificationConfidence: "Medium", notes: "State-board-specific - only relevant for that region. See Methodology re: NOT pre-setting Group Type to sameCommitment." },
  { merchant: "Electricity - Tata Power", patterns: ["TATA POWER", "TATAPOWER-DDL"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Electricity", groupType: "category", identityConfidence: "High", classificationConfidence: "Medium" },
  { merchant: "Electricity - Adani Electricity", patterns: ["ADANI ELECTRICITY", "ADANI POWER"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Electricity", groupType: "category", identityConfidence: "High", classificationConfidence: "Medium" },
  { merchant: "Electricity - BSES (Delhi)", patterns: ["BSES RAJDHANI", "BSES YAMUNA"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Electricity", groupType: "category", identityConfidence: "High", classificationConfidence: "Medium" },
  { merchant: "Electricity - MSEB / MSEDCL (Maharashtra)", patterns: ["MSEDCL", "MAHADISCOM"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Electricity", groupType: "category", identityConfidence: "High", classificationConfidence: "Medium" },
  { merchant: "Electricity bill (generic keyword)", patterns: ["ELECTRICITY BILL", "ELEC BILL", "POWER BILL"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Electricity", groupType: "category", identityConfidence: "High", classificationConfidence: "Low", notes: "Fallback keyword match only, for a state board not otherwise listed." },
  { merchant: "Piped gas - Mahanagar Gas", patterns: ["MAHANAGAR GAS", "MGL"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Gas", groupType: "category", identityConfidence: "High", classificationConfidence: "Medium" },
  { merchant: "Piped gas - Indraprastha Gas", patterns: ["INDRAPRASTHA GAS", "IGL"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Gas", groupType: "category", identityConfidence: "High", classificationConfidence: "Medium" },
  { merchant: "LPG cylinder - Indane / HP Gas / Bharat Gas", patterns: ["INDANE", "HP GAS", "BHARATGAS", "HPCL GAS"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Gas", groupType: "category", identityConfidence: "High", classificationConfidence: "Medium" },
  { merchant: "Water bill (generic keyword)", patterns: ["WATER BILL", "WATER SUPPLY", "JAL BOARD"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Water", groupType: "category", identityConfidence: "High", classificationConfidence: "Low", notes: "Municipal water billing is too locally fragmented to pre-populate by name." },
  { merchant: "Broadband - Airtel Xstream", patterns: ["AIRTEL XSTREAM", "AIRTEL BROADBAND"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Broadband/Internet", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Broadband - JioFiber", patterns: ["JIOFIBER", "JIO FIBER"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Broadband/Internet", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Broadband - ACT Fibernet", patterns: ["ACT FIBERNET", "ATRIA CONVERGENCE"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Broadband/Internet", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Broadband - Hathway", patterns: ["HATHWAY", "HATHWAY CABLE"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Broadband/Internet", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Broadband - Excitel", patterns: ["EXCITEL BROADBAND"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Broadband/Internet", groupType: "category", identityConfidence: "High", classificationConfidence: "Medium" },
  { merchant: "DTH - Tata Play", patterns: ["TATA PLAY", "TATA SKY"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "DTH/Cable TV", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Formerly Tata Sky - both name forms may appear." },
  { merchant: "DTH - Dish TV", patterns: ["DISH TV", "DISHTV"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "DTH/Cable TV", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "DTH - Airtel Digital TV", patterns: ["AIRTEL DIGITAL TV"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "DTH/Cable TV", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "DTH - Sun Direct", patterns: ["SUN DIRECT"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "DTH/Cable TV", groupType: "category", identityConfidence: "High", classificationConfidence: "Medium" },
  { merchant: "Domestic help / maid / cook", patterns: ["(person-specific - see Notes)"], merchantType: "Merchant", category: "Expense", sub: "Household", group: null, groupType: null, identityConfidence: "High", classificationConfidence: "Low", notes: "Inherently a person-to-person payment, not a merchant - can't be pre-populated at all; category/sub1 correct, no group suggested." },
  { merchant: "Rent", patterns: ["RENT", "HOUSE RENT", "RENT PAYMENT"], merchantType: "Merchant", category: "Expense", sub: "Household", group: null, groupType: null, identityConfidence: "High", classificationConfidence: "Medium", notes: "Keyword-based, not merchant-based - landlord names are person-specific. Already covered by the app's existing seed rules." },
  { merchant: "Netflix", patterns: ["NETFLIX"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: null, groupType: null, identityConfidence: "High", classificationConfidence: "High", notes: "Deliberately NOT grouped with other OTT services - see Methodology: each is already its own clean, single monthly charge, so grouping would only blur visibility, not help pattern-learning." },
  { merchant: "Amazon Prime Video / Prime", patterns: ["AMAZON PRIME", "PRIME VIDEO"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: null, groupType: null, identityConfidence: "High", classificationConfidence: "High", notes: "Same reasoning as Netflix above." },
  { merchant: "Disney+ Hotstar", patterns: ["HOTSTAR", "DISNEY HOTSTAR"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: null, groupType: null, identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "SonyLIV", patterns: ["SONYLIV"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: null, groupType: null, identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "ZEE5", patterns: ["ZEE5"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: null, groupType: null, identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "JioCinema", patterns: ["JIOCINEMA"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: null, groupType: null, identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Spotify", patterns: ["SPOTIFY"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: null, groupType: null, identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Apple Music", patterns: ["APPLE.COM/BILL", "APPLE MUSIC"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: null, groupType: null, identityConfidence: "High", classificationConfidence: "Medium", notes: "Apple billing text is often just 'APPLE.COM/BILL' with no service name - could be Music, iCloud, App Store, or Apple One. Left ungrouped and Low-confidence-adjacent for this reason." },
  { merchant: "YouTube Premium", patterns: ["YOUTUBE PREMIUM", "GOOGLE YOUTUBE"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: null, groupType: null, identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Audible", patterns: ["AUDIBLE"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: null, groupType: null, identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Google One / Google Storage", patterns: ["GOOGLE ONE", "GOOGLE STORAGE"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: null, groupType: null, identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "iCloud", patterns: ["APPLE.COM/BILL", "ICLOUD"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: null, groupType: null, identityConfidence: "High", classificationConfidence: "Medium", notes: "Same Apple billing-text ambiguity as Apple Music above." },
  { merchant: "Microsoft 365", patterns: ["MICROSOFT 365", "MSFT"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: null, groupType: null, identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Adobe Creative Cloud", patterns: ["ADOBE", "ADOBE CREATIVE CLOUD"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: null, groupType: null, identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "ChatGPT Plus / Claude Pro / AI subscriptions", patterns: ["OPENAI", "ANTHROPIC", "CHATGPT"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: null, groupType: null, identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "LinkedIn Premium", patterns: ["LINKEDIN PREMIUM"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: null, groupType: null, identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Swiggy (food delivery)", patterns: ["SWIGGY"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Eating Out", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Plain 'Swiggy' (not Instamart) is food delivery, not grocery - kept as a separate suggested group from Grocery above. The person's own data may reasonably choose to merge these; this is the generic, textbook default." },
  { merchant: "Zomato", patterns: ["ZOMATO", "ETERNAL LIMITED"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Eating Out", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Legal Entity: Eternal Limited (formerly Zomato Limited)." },
  { merchant: "EatSure / Box8 / Faasos", patterns: ["EATSURE", "BOX8", "FAASOS", "REBEL FOODS"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Eating Out", groupType: "category", identityConfidence: "High", classificationConfidence: "Medium" },
  { merchant: "Uber", patterns: ["UBER", "UBER INDIA"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Transport", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Legal Entity: Uber India Systems Private Limited." },
  { merchant: "Ola", patterns: ["OLA", "OLACABS", "ANI TECHNOLOGIES"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Transport", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Legal Entity: ANI Technologies Private Limited." },
  { merchant: "Rapido", patterns: ["RAPIDO", "ROPPEN TRANSPORT"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Transport", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Legal Entity: Roppen Transportation Services Private Limited." },
  { merchant: "Namma Yatri", patterns: ["NAMMA YATRI", "MOVING TECH"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Transport", groupType: "category", identityConfidence: "High", classificationConfidence: "Medium", notes: "Legal Entity: Moving Tech Innovations Private Limited." },
  { merchant: "BluSmart", patterns: ["BLUSMART"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Transport", groupType: "category", identityConfidence: "High", classificationConfidence: "Medium" },
  { merchant: "Indian Oil (IOCL)", patterns: ["INDIAN OIL", "IOCL", "IOC PETROL"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Fuel", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Bharat Petroleum (BPCL)", patterns: ["BHARAT PETROLEUM", "BPCL"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Fuel", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Hindustan Petroleum (HPCL)", patterns: ["HINDUSTAN PETROLEUM", "HPCL"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Fuel", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Shell", patterns: ["SHELL", "SHELL PETROL"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Fuel", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Nayara Energy", patterns: ["NAYARA ENERGY", "ESSAR PETROL"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Fuel", groupType: "category", identityConfidence: "High", classificationConfidence: "Medium", notes: "Formerly Essar - both name forms may appear." },
  { merchant: "Amazon (general shopping)", patterns: ["AMAZON", "AMAZON.IN", "AMAZON PAY"], merchantType: "Merchant", category: null, sub: "Personal", group: null, groupType: null, identityConfidence: "High", classificationConfidence: "Insufficient", notes: "Deliberately left uncategorized at Category level - Amazon spans genuine Expense/Shopping, Investment (rare), and even Bill payments via Amazon Pay. Needs per-transaction judgment; see Methodology." },
  { merchant: "Flipkart", patterns: ["FLIPKART", "FLIPKART INTERNET"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Shopping", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Legal Entity: Flipkart Internet Private Limited." },
  { merchant: "Myntra", patterns: ["MYNTRA", "MYNTRA DESIGNS"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Shopping", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Legal Entity: Myntra Designs Private Limited." },
  { merchant: "Ajio", patterns: ["AJIO", "RELIANCE AJIO", "RELIANCE RETAIL"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Shopping", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Legal Entity: Reliance Retail Limited." },
  { merchant: "Nykaa", patterns: ["NYKAA", "FSN E-COMMERCE"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Shopping", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Legal Entity: FSN E-Commerce Ventures Limited." },
  { merchant: "Meesho", patterns: ["MEESHO"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Shopping", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Tata Cliq", patterns: ["TATA CLIQ", "TATACLIQ", "TATA UNISTORE"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Shopping", groupType: "category", identityConfidence: "High", classificationConfidence: "Medium", notes: "Legal Entity: Tata Unistore Limited." },
  { merchant: "Croma", patterns: ["CROMA", "INFINITY RETAIL"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Shopping", groupType: "category", identityConfidence: "High", classificationConfidence: "Medium" },
  { merchant: "Reliance Digital", patterns: ["RELIANCE DIGITAL"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Shopping", groupType: "category", identityConfidence: "High", classificationConfidence: "Medium" },
  { merchant: "Airtel (mobile)", patterns: ["AIRTEL", "BHARTI AIRTEL"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: null, groupType: null, identityConfidence: "High", classificationConfidence: "High", notes: "Deliberately NOT grouped - most households have one line per provider, so a group adds no aggregation value; see Methodology. If the person has multiple family lines, they may prefer to group these themselves." },
  { merchant: "Jio (mobile)", patterns: ["JIO", "RELIANCE JIO", "RJIL"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: null, groupType: null, identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Vi (Vodafone Idea)", patterns: ["VI", "VODAFONE IDEA", "VODAFONE"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: null, groupType: null, identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "BSNL", patterns: ["BSNL"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: null, groupType: null, identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "PharmEasy", patterns: ["PHARMEASY", "API HOLDINGS"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Health & Pharmacy", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Tata 1mg", patterns: ["1MG", "TATA 1MG"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Health & Pharmacy", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Netmeds", patterns: ["NETMEDS", "DADHA PHARMA"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Health & Pharmacy", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Apollo Pharmacy", patterns: ["APOLLO PHARMACY"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Health & Pharmacy", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "MedPlus", patterns: ["MEDPLUS", "MEDPLUS HEALTH"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Health & Pharmacy", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Practo (consultation booking)", patterns: ["PRACTO"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Health & Pharmacy", groupType: "category", identityConfidence: "High", classificationConfidence: "Medium" },
  { merchant: "Cult.fit / CureFit", patterns: ["CULTFIT", "CURE.FIT", "CULT.FIT"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Fitness", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Gold's Gym", patterns: ["GOLDS GYM"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Fitness", groupType: "category", identityConfidence: "High", classificationConfidence: "Medium" },
  { merchant: "Anytime Fitness", patterns: ["ANYTIME FITNESS"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Fitness", groupType: "category", identityConfidence: "High", classificationConfidence: "Medium" },
  { merchant: "Decathlon", patterns: ["DECATHLON"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Fitness", groupType: "category", identityConfidence: "High", classificationConfidence: "Medium", notes: "Sporting goods retailer, not a membership - grouped here as the closest fit, but genuinely borderline vs. general Shopping." },
  { merchant: "BYJU'S", patterns: ["BYJUS", "THINK AND LEARN"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Education", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Unacademy", patterns: ["UNACADEMY"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Education", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Vedantu", patterns: ["VEDANTU"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Education", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "upGrad", patterns: ["UPGRAD"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Education", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Coursera", patterns: ["COURSERA"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Education", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Udemy", patterns: ["UDEMY"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Education", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Physics Wallah", patterns: ["PHYSICS WALLAH", "PW"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Education", groupType: "category", identityConfidence: "High", classificationConfidence: "Medium" },
  { merchant: "MakeMyTrip", patterns: ["MAKEMYTRIP", "MMT", "MAKEMYTRIP INDIA"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Travel", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Legal Entity: MakeMyTrip (India) Private Limited." },
  { merchant: "Yatra", patterns: ["YATRA", "YATRA ONLINE"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Travel", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Goibibo", patterns: ["GOIBIBO"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Travel", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Cleartrip", patterns: ["CLEARTRIP"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Travel", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "IRCTC (train booking)", patterns: ["IRCTC"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Travel", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "IndiGo", patterns: ["INDIGO", "INTERGLOBE AVIATION"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Travel", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Air India", patterns: ["AIR INDIA"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Travel", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "SpiceJet", patterns: ["SPICEJET"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Travel", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Vistara", patterns: ["VISTARA", "TATA SIA AIRLINES"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Travel", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "OYO", patterns: ["OYO", "OYO ROOMS"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Travel", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Airbnb", patterns: ["AIRBNB"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Travel", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Booking.com", patterns: ["BOOKING.COM"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Travel", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Agoda", patterns: ["AGODA"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Travel", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "HDFC Life", patterns: ["HDFC LIFE", "HDFC LIFE INSURANCE"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Insurance Premium", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "ICICI Prudential Life", patterns: ["ICICI PRU LIFE", "ICICI PRUDENTIAL LIFE"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Insurance Premium", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Max Life Insurance", patterns: ["MAX LIFE"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Insurance Premium", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Star Health Insurance", patterns: ["STAR HEALTH"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Insurance Premium", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "HDFC ERGO", patterns: ["HDFC ERGO"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Insurance Premium", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Bajaj Allianz", patterns: ["BAJAJ ALLIANZ"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Insurance Premium", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "ACKO", patterns: ["ACKO", "ACKO GENERAL INSURANCE"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Insurance Premium", groupType: "category", identityConfidence: "High", classificationConfidence: "High" },
  { merchant: "Policybazaar (aggregator)", patterns: ["POLICYBAZAAR", "PB FINTECH"], merchantType: "Merchant", category: null, sub: null, group: null, groupType: null, identityConfidence: "High", classificationConfidence: "Insufficient", notes: "An aggregator/marketplace, not the insurer itself - the actual policy issuer is usually the more useful merchant to record, when identifiable from the same transaction." },
  { merchant: "Credit card bill payment (generic)", patterns: ["CRED", "CC PAYMENT", "CREDIT CARD PAYMENT", "BILLDESK CC", "DREAMPLUG"], merchantType: "Merchant", category: "Transfer", sub: null, group: null, groupType: null, identityConfidence: "High", classificationConfidence: "High", notes: "Already covered by the app's existing seed rules (\"credit card payment\", \"cc payment\") - listed here for completeness, not a new addition. Legal Entity: Dreamplug Technologies Private Limited." },
  { merchant: "CRED (bill payment app)", patterns: ["CRED", "CRED CLUB", "DREAMPLUG"], merchantType: "Merchant", category: "Transfer", sub: null, group: null, groupType: null, identityConfidence: "High", classificationConfidence: "Medium", notes: "CRED itself is a payment app used to pay OTHER credit card bills - the underlying card issuer, if identifiable, is more useful to record than 'CRED' itself." },
  { merchant: "Self / own-account transfer (generic)", patterns: ["SELF TRANSFER", "OWN ACCOUNT", "IMPS SELF", "NEFT SELF"], merchantType: "Merchant", category: "Transfer", sub: null, group: null, groupType: null, identityConfidence: "High", classificationConfidence: "High", notes: "Already covered by the app's existing seed rules - listed for completeness." },
  { merchant: "Salary (generic keyword)", patterns: ["SALARY", "SAL CREDIT"], merchantType: "Merchant", category: "Income", sub: null, group: null, groupType: null, identityConfidence: "High", classificationConfidence: "High", notes: "Employer names are inherently person-specific and cannot be pre-populated by a generic library - already covered by the app's existing pattern-based seed rules." },
  { merchant: "Interest credit (generic keyword)", patterns: ["INTEREST CREDIT", "INT.PD", "INT CR"], merchantType: "Merchant", category: "Income", sub: null, group: null, groupType: null, identityConfidence: "High", classificationConfidence: "High", notes: "Bank-specific interest-credit phrasing varies but is pattern-based, not merchant-based - already covered." },
  { merchant: "Dividend credit (generic keyword)", patterns: ["DIVIDEND", "DIV CREDIT"], merchantType: "Merchant", category: "Income", sub: null, group: null, groupType: null, identityConfidence: "High", classificationConfidence: "High", notes: "Already covered." },
  { merchant: "BB Now / BigBasket Instant", patterns: ["BBNOW", "BIGBASKET NOW"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Grocery", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Quick commerce arm of BigBasket / Tata." },
  { merchant: "Country Delight", patterns: ["COUNTRY DELIGHT", "COUNTRYDELIGHT", "DAILY DAIRY", "BEEHIVE CAPITAL"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Grocery", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Daily milk and fresh produce subscription. Legal Entity: Beehive Capital Advisors Private Limited." },
  { merchant: "BBDaily / DailyNinja", patterns: ["BBDAILY", "DAILYNINJA"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Grocery", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Subscription grocery & milk delivery service." },
  { merchant: "NETC Fastag / Tolls", patterns: ["NETC FASTAG", "IHMCL", "FASTAG", "NHAI", "PAYTM FASTAG"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Transport", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Automated highway toll payments." },
  { merchant: "Metro Rail (BMRCL / DMRC / MMOPL)", patterns: ["BMRCL", "DMRC", "MMOPL", "MAHA METRO", "METRO RECHARGE"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Transport", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "City metro train smartcard recharges and QR tickets." },
  { merchant: "InDrive", patterns: ["INDRIVE", "INDRIVER"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Transport", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Ride-hailing aggregator." },
  { merchant: "Park+", patterns: ["PARK+", "PARKPLUS", "PARKING"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Transport", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Parking payments, Fastag recharge, and auto utility app." },
  { merchant: "redBus / AbhiBus", patterns: ["REDBUS", "ABHIBUS", "BUS INDIA"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Travel", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Inter-city bus ticketing platform." },
  { merchant: "Bajaj Finance / Finserv EMI", patterns: ["BAJAJ FINANCE", "BAJAJ FINSERV", "BAJAJ AUTO FIN"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "EMI & Debt Repayment", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Consumer durable loans and personal loan EMI payments." },
  { merchant: "Home First / Housing Finance EMI", patterns: ["HOME FIRST", "LIC HOUSING", "HDFC HOME LOAN", "CANFIN"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "EMI & Debt Repayment", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Home loan EMI debits." },
  { merchant: "OneCard / Slice / Uni Card Repayment", patterns: ["ONECARD", "SLICE", "UNI CARD", "CREDITBEE"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "EMI & Debt Repayment", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Fintech credit cards / Pay-Later repayments." },
  { merchant: "Niva Bupa Health Insurance", patterns: ["NIVA BUPA", "MAX BUPA"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Insurance Premium", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Standalone health insurance provider." },
  { merchant: "Care Health Insurance", patterns: ["CARE HEALTH", "RELIGARE HEALTH"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Insurance Premium", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Standalone health insurance provider." },
  { merchant: "Tata AIG / Go Digit", patterns: ["TATA AIG", "DIGIT INSURANCE", "GO DIGIT"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Insurance Premium", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "General, motor, and health insurance." },
  { merchant: "Dr. Lal PathLabs / Metropolis / Thyrocare", patterns: ["LAL PATHLABS", "METROPOLIS", "THYROCARE", "REDCLIFFE"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Health & Pharmacy", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Diagnostic lab chains and home sample collection." },
  { merchant: "Starbucks / Third Wave / Blue Tokai", patterns: ["STARBUCKS", "THIRDWAVE", "BLUE TOKAI", "TATA STARBUCKS"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Eating Out", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Specialty coffee and cafe chains." },
  { merchant: "McDonald's / Domino's / KFC", patterns: ["WESTLIFE", "JUBILANT FOODWORKS", "DEVYANI", "SAPPHIRE", "MCDONALDS", "DOMINOS", "KFC"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Eating Out", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Major quick-service restaurant (QSR) chains." },
  { merchant: "Zara / H&M / Uniqlo", patterns: ["ZARA", "H&M", "H AND M", "UNIQLO"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Shopping", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Fast-fashion retail stores and e-commerce." },
  { merchant: "Trends / Westside / Max Fashion", patterns: ["RELIANCE TRENDS", "TRENT", "WESTSIDE", "MAX FASHION", "LANDMARK GROUP"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Shopping", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Departmental apparel retail." },
  { merchant: "Tira / Purplle / Mamaearth", patterns: ["TIRA BEAUTY", "PURPLLE", "MAMAEARTH", "HONASA"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Shopping", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Beauty and personal care e-commerce." },
  { merchant: "Wint Wealth / Grip Invest / Dezerv", patterns: ["WINT WEALTH", "GRIP INVEST", "DEZERV"], merchantType: "Investment Platform", category: "Investment", sub: "Wealth Building", group: "Fixed Income & Bonds", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Bonds, corporate debt, and curated wealth management platforms." },
  { merchant: "Snabbit", patterns: ["SNABBIT", "MAESTRO SOLUTIONS", "MAESTRO SOLUTIONS PVT LTD"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Grocery", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Legal Entity: Maestro Solutions Private Limited. Home services / quick delivery." },
  { merchant: "Dunzo", patterns: ["DUNZO", "DUNZO DIGITAL"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Grocery", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Legal Entity: Dunzo Digital Private Limited." },
  { merchant: "PhonePe", patterns: ["PHONEPE", "FX MART", "FXMART"], merchantType: "Payment Aggregator", category: null, sub: null, group: null, groupType: "category", identityConfidence: "High", classificationConfidence: "Insufficient", notes: "Legal Entity: PhonePe India Private Limited (formerly FX Mart). OVERRIDDEN from source spreadsheet suggestion \"Transfer\"/\"Personal\"/\"Wallet & UPI\" - see file header." },
  { merchant: "Razorpay", patterns: ["RAZORPAY", "RZPX", "RAZORPAY SOFTWARE"], merchantType: "Payment Aggregator", category: null, sub: null, group: null, groupType: "category", identityConfidence: "High", classificationConfidence: "Insufficient", notes: "Legal Entity: Razorpay Software Private Limited. Aggregator / Payment Gateway. OVERRIDDEN from source spreadsheet suggestion \"Expense\"/\"Personal\"/\"Payment Gateway\" - see file header." },
  { merchant: "Jupiter Money", patterns: ["JUPITER", "AMICA FINANCIAL"], merchantType: "Financial Institution", category: null, sub: null, group: null, groupType: "category", identityConfidence: "High", classificationConfidence: "Insufficient", notes: "Legal Entity: Amica Financial Technologies Private Limited. OVERRIDDEN from source spreadsheet suggestion \"Expense\"/\"Personal\"/\"Fintech / Banking\" - see file header." },
  { merchant: "Fi Money / EpiFi", patterns: ["FI MONEY", "EPIFI TECHNOLOGIES"], merchantType: "Financial Institution", category: null, sub: null, group: null, groupType: "category", identityConfidence: "High", classificationConfidence: "Insufficient", notes: "Legal Entity: Epifi Technologies Private Limited. OVERRIDDEN from source spreadsheet suggestion \"Expense\"/\"Personal\"/\"Fintech / Banking\" - see file header." },
  { merchant: "Lenskart", patterns: ["LENSKART", "LENSKART SOLUTIONS"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Shopping", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Legal Entity: Lenskart Solutions Private Limited." },
  { merchant: "Urban Company / UrbanClap", patterns: ["URBAN COMPANY", "URBANCLAP"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Home Services", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Legal Entity: UrbanClap Technologies India Private Limited." },
  { merchant: "BookMyShow", patterns: ["BOOKMYSHOW", "BIG TREE ENTERTAINMENT", "BIGTREE"], merchantType: "Merchant", category: "Expense", sub: "Personal", group: "Entertainment", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Legal Entity: Big Tree Entertainment Private Limited." },
  { merchant: "Mygate", patterns: ["MYGATE", "VIVISH TECHNOLOGIES"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Housing & Maintenance", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Legal Entity: Vivish Technologies Private Limited." },
  { merchant: "NoBroker / NoBrokerhood", patterns: ["NOBROKER", "NOBROKERHOOD", "NOBROKER TECHNOLOGIES"], merchantType: "Merchant", category: "Expense", sub: "Household", group: "Housing & Maintenance", groupType: "category", identityConfidence: "High", classificationConfidence: "High", notes: "Legal Entity: NoBroker Technologies Solutions Private Limited." },
];

export default MERCHANT_LIBRARY_V2;
