import { useState, useEffect, useRef, useMemo } from "react";
import { ONB_CSS } from "./onbStyles.js";
import * as T from "./journeyTemplates.generated.js";
import { STEPS as JOURNEY_STEPS, buildJourney } from "./journeyFromEngine.js";
import { patchForAnswer, REPEAT_CADENCE } from "../inference/onboardingResult.js";

/**
 * Onboarding + demo journey (backlog #38/#39/#70), ported screen-for-screen from
 * the 29 Sep journey prototype artifact (journey-prototype-v1.html, verified
 * byte-identical to the file read here). Two rules, learned the hard way on this
 * project, are followed deliberately:
 *   1. The CSS is NOT retyped. `onbStyles.js` is generated by
 *      tools/extract_onb_css.py straight from the artifact - same class names,
 *      same values - so "looks like the mockup" is a property of the source, not
 *      of my memory of it.
 *   2. Markup mirrors the prototype's own (kicker / h2 / hint / choices / choice /
 *      row / btn / link / meet / feed / bar / legend / qcard ...), so those rules
 *      apply as written.
 *
 * Deliberately NOT carried over, because they are prototype annotations rather
 * than product: the "Restart prototype" link, the "Prototype control" month
 * picker on the statement screen, the "(prototype shows N of M)" note on the
 * quick-review counter, and the "Draft wording" tags.
 *
 * Demo screens (meet / reading / sorted / quick) use the prototype's scripted
 * Asha narrative (DEMO_DATA below) exactly as the prototype does - it is a story
 * layer, "every number is made up, every behaviour is real". The REAL path does
 * not use it: the statement step hands off to the app's own Upload view.
 */

const BASE_CSS = `
@import url('https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,600;1,9..144,500&family=IBM+Plex+Sans:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500;600&display=swap');
.onb-root{ --paper:#ECE7DA; --card:#F9F7F1; --ink:#21262B; --ink-soft:#57616B; --line:#D3CAB5; --line-strong:#A9A08A;
  --teal:#2E6659; --ochre:#A8703A; --tint:rgba(46,102,89,.075); --tint-line:rgba(46,102,89,.28);
  margin:0; font-family:'IBM Plex Sans',sans-serif; font-size:16px; color:var(--ink); background:var(--paper);
  background-image: repeating-linear-gradient(to bottom, rgba(85,96,107,0.045) 0px, rgba(85,96,107,0.045) 1px, transparent 1px, transparent 34px);
  min-height:100vh; padding: 24px 22px 36px; -webkit-font-smoothing:antialiased; }
.onb-root, .onb-root *{ box-sizing:border-box; }
.onb-root [hidden]{ display:none !important; }
/* Used when these choice cards are embedded inside another screen (Home) rather than owning the page. */
.onb-root.embed{ background:none; min-height:0; padding:0; }
.onb-root.embed .wrap{ max-width:none; }
`;

/** Renders the shared stylesheet. Exported so Home can embed the SAME choice cards. */
export function OnbStyle() { return <style>{BASE_CSS + ONB_CSS}</style>; }

const IC = {
  user: '<circle cx="12" cy="7" r="4"/><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/>',
  heart: '<path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/>',
  smile: '<circle cx="12" cy="12" r="10"/><path d="M8 14s1.5 2 4 2 4-2 4-2"/><line x1="9" y1="9" x2="9.01" y2="9"/><line x1="15" y1="9" x2="15.01" y2="9"/>',
  users: '<path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/>',
  dots: '<circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/><circle cx="5" cy="12" r="1"/>',
  shield: '<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>',
  trend: '<polyline points="23 6 13.5 15.5 8.5 10.5 1 18"/><polyline points="17 6 23 6 23 12"/>',
  home: '<path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/>',
  book: '<path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"/><path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"/>',
  sun: '<circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/>',
  down: '<circle cx="12" cy="12" r="10"/><line x1="8" y1="12" x2="16" y2="12"/>',
  upload: '<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/>',
  check: '<polyline points="20 6 9 17 4 12"/>',
  lock: '<rect x="3" y="11" width="18" height="11" rx="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/>',
};
// Same markup the prototype's icon() produces. Path data lives in plain strings (not module-level JSX) -
// see backlog #67 for the bug that module-level JSX caused.
export function Icon({ name, className, style }) {
  return <svg className={className} style={style} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" dangerouslySetInnerHTML={{ __html: IC[name] }} />;
}

export const HOUSE = [["me", "user", "Just me"], ["partner", "heart", "Partner or spouse"], ["kids", "smile", "Children"], ["parents", "users", "Parents"], ["other", "dots", "Someone else"]];
export const PRIO = [["security", "shield", "Building financial security"], ["wealth", "trend", "Building wealth"], ["home", "home", "Buying a home"], ["edu", "book", "Children\u2019s education"], ["retire", "sun", "Retirement"], ["debt", "down", "Clearing debt"], ["other", "dots", "Something else"]];

/** The prototype's `.choices` / `.choice` cards. Used by onboarding Q1/Q2 AND Home's inline profile questions. */
export function ChoiceGrid({ options, isSelected, onToggle, disabledKey, isDisabled }) {
  return (
    <div className="choices">
      {options.map(([key, iconName, label]) => {
        const sel = isSelected(key);
        return (
          <button key={key} className={"choice" + (sel ? " sel" : "")} aria-pressed={sel} disabled={!!(isDisabled && isDisabled(key))} style={isDisabled && isDisabled(key) ? { opacity: 0.45 } : undefined} onClick={() => { if (key !== disabledKey) onToggle(key); }}>
            <Icon name={iconName} className="ic" />
            <span className="ct">{label}</span>
          </button>
        );
      })}
    </div>
  );
}

/** "What matters most right now?" - choose up to 3, kept in the order picked (the first is the top priority). Used here and on Home. */
export function PriorityPicker({ value, onChange }) {
  const sel = value || [];
  const toggle = (k) => onChange(sel.includes(k) ? sel.filter((x) => x !== k) : sel.length < 3 ? [...sel, k] : sel);
  return (
    <>
      <ChoiceGrid options={PRIO} isSelected={(k) => sel.includes(k)} onToggle={toggle} isDisabled={(k) => sel.length >= 3 && !sel.includes(k)} />
      <p className="fine" style={{ marginTop: 10 }} aria-live="polite">{sel.length} of 3 chosen{sel.length ? " \u00B7 the first you picked is your top priority" : ""}</p>
    </>
  );
}

/* ---- The prototype's scripted Asha narrative: DATA[h] (only h=1 is used until the demo stepper lands) ---- */
export const DEMO_DATA = {
  1: { tx: 68, merchants: 31, sorted: 19, quick: 8, need: 4, cov: 71, span: "1 Sep to 28 Sep", known: 22,
       incomeLine: "Spotted your income \u2014 a <b>salary</b> of \u20B91,10,000 on 1 Sep",
       billsLine: "Found <b>5 payments</b> that look like monthly bills \u2014 we\u2019ll confirm once we see another month" },
};
const QUICK_SCRIPT = [
  { name: "Zepto", meta: "8 payments \u00B7 \u20B96,511 \u00B7 last 21 Aug", guess: "Grocery", tag: "Household", conf: "High" },
  { name: "Blinkit", meta: "4 payments \u00B7 \u20B93,230 \u00B7 last 12 Aug", guess: "Grocery", tag: "Household", conf: "High" },
  { name: "Netflix", meta: "6 payments \u00B7 \u20B93,894 \u00B7 last 3 Sep", guess: "A monthly subscription", tag: "Personal", conf: "High" },
  { name: "Bangalore Electricity (BESCOM)", meta: "5 payments \u00B7 \u20B919,240 \u00B7 last 23 Jun", guess: "Electricity", tag: "Household", conf: "Medium" },
  { name: "UPI \u00B7 R Sharma", meta: "6 payments \u00B7 \u20B99,000 \u00B7 last 5 Sep", guess: null, choices: ["Household help", "Rent", "Family", "Friends", "Something else"] },
  { name: "Sri Krishna Sweets", meta: "3 payments \u00B7 \u20B91,140 \u00B7 last 14 Aug", guess: null, choices: ["Eating out", "Groceries", "Gifts", "Something else"] },
];
const CHANGE = ["Grocery", "Eating out", "Shopping", "Transport", "Bills & utilities", "Subscription", "Health", "Something else"];

const reducedMotion = () => typeof window !== "undefined" && window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches;

/* ------------------------------------------------------------------ screens */

function Welcome({ go, onTryDemo, onGoHome }) {
  return (
    <>
      {onGoHome && (
        <div className="card tint" style={{ marginBottom: 22 }}>
          <div className="lbl">Welcome back</div>
          <p className="muted" style={{ marginBottom: 14 }}>Your money is already on this device.</p>
          <button className="btn teal" onClick={onGoHome}>Go to my Home {"\u2192"}</button>
        </div>
      )}
      <div className="eyebrow">Being Wealthy</div>
      <h1>See your money clearly.<em>Understand where it goes, where you stand, and what{"\u2019"}s coming next.</em></h1>
      <div className="trust">
        <span className="tic"><Icon name="lock" /></span>
        <div>
          <div className="tt">Private by design.</div>
          <div className="td">Everything you add is saved only on this device. No account needed, and your statements are never stored on our servers.</div>
          <details><summary>How does this work?</summary><div className="body">Your numbers live in this browser, on your device. CSV files never leave it. To read a PDF, its pages are sent securely to our reader, which doesn{"\u2019"}t keep them afterward.</div></details>
        </div>
      </div>
      <div className="paths">
        <div className="path"><div className="pt">Start with my money</div><div className="pd">Add one bank or card statement and see your own picture.</div><div className="pm">About 3 minutes</div><button className="btn full" onClick={() => go("statement")}>Start</button></div>
        <div className="path"><div className="pt">Explore Being Wealthy</div><div className="pd">Try everything with a sample person. Nothing of yours needed.</div><div className="pm">~2 minutes &middot; No data required</div><button className="btn ghost full" onClick={onTryDemo}>Explore</button></div>
      </div>
    </>
  );
}

function Q1({ go, household, setHousehold, setHouseholdAnswered, embedded }) {
  return (
    <>
      {!embedded && <button className="back" onClick={() => go("welcome")}>{"\u2190"} Back</button>}
      <div className="kicker">Question 1 of 2</div>
      <h2>Who{"\u2019"}s part of your financial life?</h2>
      <p className="hint">Pick everyone you support or plan with. It helps put your numbers in context, and you can change it anytime.</p>
      <ChoiceGrid options={HOUSE} disabledKey="me" isSelected={(k) => !!household[k]} onToggle={(k) => setHousehold({ ...household, [k]: !household[k] })} />
      <div className="row">
        {/* Only "Continue" is a confirmed answer; "Skip for now" leaves it open so Home can ask later (backlog #66). */}
        <button className="btn" onClick={() => { setHouseholdAnswered(true); go("q2"); }}>Continue</button>
        <button className="link" onClick={() => go("q2")}>Skip for now</button>
      </div>
    </>
  );
}

function Q2({ go, priorities, setPriorities, embedded }) {
  return (
    <>
      {!embedded && <button className="back" onClick={() => go("q1")}>{"\u2190"} Back</button>}
      <div className="kicker">Question 2 of 2</div>
      <h2>What matters most right now? Choose up to 3</h2>
      <p className="hint">We{"\u2019"}ll use your first pick to start you off with a first goal, and the others to shape what Home shows you.</p>
      <PriorityPicker value={priorities} onChange={setPriorities} />
      <div className="row">
        <button className="btn" disabled={!(priorities && priorities.length)} onClick={() => go("statement")}>Continue</button>
        <button className="link" onClick={() => go("statement")}>Skip for now</button>
      </div>
    </>
  );
}

function Statement({ go, onPickFile, onTryDemo, why, onBack }) {
  const [over, setOver] = useState(false);
  // `why`: opened from a Home next step - say what this statement is for and what it will add.
  const inputRef = useRef(null);
  const pick = (file) => { if (!file) return; onPickFile(file); go("intake"); }; // the file is read right here, on the next screen
  return (
    <>
      <button className="back" onClick={() => (onBack ? onBack() : go("welcome"))}>{"\u2190"} {onBack ? "Back to Home" : "Back"}</button>
      <div className="kicker">{why ? "Add another account" : "Let\u2019s begin"}</div>
      <h2>{why ? why.title : "Add your bank statement"}</h2>
      <p className="hint" data-testid="statement-why">{why ? why.why : "A bank account statement as a PDF, CSV or Excel file. Cards, loans and investments can be added right after."}</p>
      <input ref={inputRef} type="file" accept=".pdf,.csv,.xlsx,.xls" style={{ display: "none" }} onChange={(e) => pick(e.target.files && e.target.files[0])} />
      <div className={"drop" + (over ? " over" : "")} role="button" tabIndex={0}
        onClick={() => inputRef.current && inputRef.current.click()} onKeyDown={(e) => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); inputRef.current && inputRef.current.click(); } }}
        onDragEnter={(e) => { e.preventDefault(); setOver(true); }} onDragOver={(e) => { e.preventDefault(); setOver(true); }}
        onDragLeave={(e) => { e.preventDefault(); setOver(false); }} onDrop={(e) => { e.preventDefault(); setOver(false); pick(e.dataTransfer && e.dataTransfer.files && e.dataTransfer.files[0]); }}>
        <Icon name="upload" className="big-ic" />
        <div className="t">Drop a statement here</div><div className="s">PDF, CSV or Excel {"\u00B7"} one account at a time</div>
        <button className="btn" onClick={(e) => { e.stopPropagation(); inputRef.current && inputRef.current.click(); }}>Choose a file</button>
      </div>
      {!why && <div className="row" style={{ marginTop: 14 }}><button className="link" onClick={onTryDemo}>No statement handy? Use the demo statement instead</button></div>}
      <details><summary>What happens to my file?</summary><div className="body">Your statements and numbers are saved only on this device. CSV and Excel files never leave it. To read a PDF, its pages are sent from your browser to Google{"\u2019"}s Gemini reader using your own key, and are not kept.</div></details>
      <details><summary>Tip: get several months in one go</summary><div className="body">Most banks let you download 6{"\u2013"}12 months in a single file from net banking. It{"\u2019"}s the fastest way to help us spot your patterns.</div></details>
    </>
  );
}

/** The statement is being read in place: real steps as they happen, the two profile questions while we wait, and - only if needed -
 *  the password, the key or the problem, right here. */
function Intake({ go, status, controlRef, onPickFile, onToast, addMode, ready, household, setHousehold, householdAnswered, setHouseholdAnswered, priorities, setPriorities }) {
  const [pwd, setPwd] = useState("");
  const [key, setKey] = useState("");
  const inputRef = useRef(null);
  const [q, setQ] = useState(() => (addMode ? "done" : !householdAnswered ? "q1" : !(priorities && priorities.length) ? "q2" : "done"));
  // The steps are folded from every status the reader reported, so even an instant read shows each real step it took.
  const steps = [];
  ((status && status.log) || []).forEach((e) => {
    if (e.stage === "imported") { steps.forEach((x) => { x.done = true; }); steps.push({ stage: "saved", label: "Saved " + e.count + " transactions on this device", done: true }); return; }
    if (!e.label || ["error", "needs_key", "needs_password"].includes(e.stage)) return;
    steps.forEach((x) => { x.done = true; });
    const i = steps.findIndex((x) => x.stage === e.stage);
    if (i >= 0) { steps[i].label = e.label; steps[i].done = false; } else steps.push({ stage: e.stage, label: e.label, done: false });
  });
  useEffect(() => { if (ready && q === "done") go("reading"); }, [ready, q]); // eslint-disable-line react-hooks/exhaustive-deps
  const stage = status ? status.stage : null;
  const unreconciled = stage === "unreconciled";
  const stalled = ["error", "needs_key", "needs_password", "unreconciled"].includes(stage);
  const inr = (n) => "\u20B9" + Math.abs(Math.round(n)).toLocaleString("en-IN");
  useEffect(() => { if (unreconciled && onToast) onToast("This statement doesn\u2019t add up. Please check it."); }, [unreconciled]); // eslint-disable-line react-hooks/exhaustive-deps
  const qGo = (to) => setQ((cur) => (cur === "q1" ? (priorities && priorities.length ? "done" : "q2") : "done"));
  return (
    <>
      <input ref={inputRef} type="file" accept=".pdf,.csv,.xlsx,.xls" style={{ display: "none" }} onChange={(e) => { const f = e.target.files && e.target.files[0]; e.target.value = ""; if (f) onPickFile(f); }} />
      <div className="kicker">{ready ? "Done reading" : stalled ? "One thing first" : "One moment"}</div>
      <h2>{ready ? "Your statement is read" : "Reading your statement\u2026"}</h2>
      <div className="feed" aria-live="polite">
        {steps.map((x, i) => (
          <div key={x.stage + i} className="ln show">{x.done ? <Icon name="check" /> : stalled ? <Icon name="dots" /> : <span className="spin" />}<span>{x.label}</span></div>
        ))}
      </div>
      {stage === "needs_password" && (
        <div className="card" role="alert">
          <div className="lbl">This PDF is password-protected</div>
          <p className="hint" style={{ marginTop: 0 }}>{status.wrong ? "That password didn\u2019t work. " : ""}Banks usually use your date of birth or customer ID. The password stays in this browser.</p>
          <div className="row" style={{ gap: 10 }}>
            <input type="password" aria-label="PDF password" value={pwd} onChange={(e) => setPwd(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && pwd) controlRef.current.submitPassword(pwd); }}
              style={{ flex: 1, padding: "10px 12px", borderRadius: 10, border: "1px solid var(--line, #ddd)", font: "inherit" }} />
            <button className="btn teal" disabled={!pwd} onClick={() => controlRef.current.submitPassword(pwd)}>Unlock</button>
          </div>
        </div>
      )}
      {(stage === "needs_key" || (stage === "error" && status.canAddKey)) && (
        <div className="card" role="alert">
          <div className="lbl">{stage === "needs_key" ? "Reading a PDF needs your Gemini key" : status.message}</div>
          <p className="hint" style={{ marginTop: 0 }}>The key is free from Google, is kept only in this browser, and is used only to read statements. CSV and Excel files don{"\u2019"}t need one. <a href="https://aistudio.google.com/app/apikey" target="_blank" rel="noreferrer">Get a free key</a></p>
          <div className="row" style={{ gap: 10 }}>
            <input type="password" aria-label="Gemini API key" placeholder="Paste your Gemini API key" value={key} onChange={(e) => setKey(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && key.trim()) controlRef.current.submitKey(key); }}
              style={{ flex: 1, padding: "10px 12px", borderRadius: 10, border: "1px solid var(--line, #ddd)", font: "inherit" }} />
            <button className="btn teal" disabled={!key.trim()} onClick={() => controlRef.current.submitKey(key)}>Save and continue</button>
          </div>
        </div>
      )}
      {unreconciled && (
        <div className="card" role="alert" data-testid="unreconciled" style={{ borderColor: "#9c4a34", background: "rgba(156,74,52,0.07)" }}>
          <div className="lbl" style={{ color: "#9c4a34" }}>This statement doesn{"\u2019"}t add up</div>
          {status.csv ? (
            <p className="hint" style={{ marginTop: 0 }}>The running balance in this file breaks in {status.breaks} place{status.breaks === 1 ? "" : "s"}, so a row may be missing or misread. Your cash and anything built on it could be wrong.</p>
          ) : (
            <p className="hint" style={{ marginTop: 0 }}>
              {status.opening !== null && status.opening !== undefined ? <>{status.isCard ? "Previous balance" : "Opening"} {inr(status.opening)}, plus the {status.count} transactions I read, comes to {inr(status.implied)}. </> : null}
              The statement says {status.isCard ? "outstanding" : "closing"} {inr(status.closing)}. That is {inr(status.diff)} {status.diff > 0 ? "more" : "less"} than it should be{status.gaps ? ", with " + status.gaps + " jump" + (status.gaps === 1 ? "" : "s") + " in the running balance" : ""}. A transaction may be missing or misread, so your cash and anything built on it could be wrong.
            </p>
          )}
          <div className="row" style={{ gap: 10 }}>
            <button className="btn ghost" onClick={() => inputRef.current && inputRef.current.click()}>Check the file</button>
            <button className="btn teal" data-testid="continue-anyway" onClick={() => controlRef.current && controlRef.current.proceedAnyway && controlRef.current.proceedAnyway()}>Continue anyway</button>
          </div>
        </div>
      )}
      {stage === "error" && !status.canAddKey && (
        <div className="card" role="alert"><div className="lbl">I couldn{"\u2019"}t use that file</div><p className="hint" style={{ margin: 0 }}>{status.message}</p></div>
      )}
      {stalled && !unreconciled && <div className="row" style={{ marginTop: 14 }}><button className="btn ghost" onClick={() => inputRef.current && inputRef.current.click()}>Choose a different file</button></div>}
      {ready && q !== "done" && <div className="row" style={{ marginTop: 14 }}><button className="btn big" onClick={() => go("reading")}>Show my picture {"\u2192"}</button><span className="muted" style={{ marginLeft: 10 }}>or answer these first</span></div>}
      {q !== "done" && !stalled && (
        <div className="card" style={{ marginTop: 18 }}>
          <div className="lbl">While I read this{"\u2026"}</div>
          {q === "q1" && <Q1 go={qGo} embedded household={household} setHousehold={setHousehold} setHouseholdAnswered={setHouseholdAnswered} />}
          {q === "q2" && <Q2 go={qGo} embedded priorities={priorities} setPriorities={setPriorities} />}
        </div>
      )}
      {q !== "done" && stalled && <p className="fine" style={{ marginTop: 14 }}>Your answers are saved as you go. You can finish these later on Home.</p>}
    </>
  );
}

function Meet({ go }) {
  return (
    <>
      <div className="kicker">Demo</div>
      <h2>Meet Asha</h2>
      <div className="meet"><div className="avatar">A</div><div>
        <p><strong>34, works in Bengaluru.</strong> Supports her partner and daughter. Saving for a home.</p>
        <p>Asha has just added her first statement: <strong>one month</strong>, September. Later you can watch what changes as she adds more {"\u2014"} every number is made up, every behaviour is real.</p>
      </div></div>
      <button className="btn big" onClick={() => go("reading")}>Read Asha{"\u2019"}s statement {"\u2192"}</button>
    </>
  );
}

function Reading({ go, d, live, accountName }) {
  const [shown, setShown] = useState(0);
  const [waitShown, setWaitShown] = useState(false);
  const [done, setDone] = useState(false);
  const [cnt, setCnt] = useState(0);
  const finishedRef = useRef(false);
  const LINES = 5, RED = reducedMotion();
  useEffect(() => {
    const timers = [];
    const later = (fn, ms) => timers.push(setTimeout(fn, RED ? 0 : ms));
    for (let i = 0; i < LINES; i++) {
      later(() => {
        setShown((s) => Math.max(s, i + 1));
        if (i === 1) { // count up the transactions, same easing as the prototype's countUp
          if (RED) { setCnt(d.tx); return; }
          let start = null;
          const step = (ts) => { if (!start) start = ts; const p = Math.min(1, (ts - start) / 1000); setCnt(Math.round(d.tx * (1 - Math.pow(1 - p, 3)))); if (p < 1) requestAnimationFrame(step); };
          requestAnimationFrame(step);
        }
      }, 500 + i * 1100);
    }
    later(() => setWaitShown(true), 500 + LINES * 1100);
    later(() => { if (finishedRef.current) return; finishedRef.current = true; setDone(true); timers.push(setTimeout(() => go("sorted"), RED ? 0 : 900)); }, 500 + LINES * 1100 + 900);
    return () => timers.forEach(clearTimeout);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  const ln = (i) => "ln" + (shown > i ? " show" : "");
  return (
    <>
      <div className="kicker">{live ? "One moment" : <>Demo {"\u00B7"} One moment</>}</div>
      <h2>{live ? <>Reading your statement{"\u2026"}</> : <>Reading Asha{"\u2019"}s statement{"\u2026"}</>}</h2>
      <div className="feed">
        <div className={ln(0)}><Icon name="check" /><span>Identified <b>{live ? accountName || "your bank" : "Sample Bank"}</b> {live ? "account" : "savings account"}</span></div>
        <div className={ln(1)}><Icon name="check" /><span>Found <span className="num">{cnt}</span> transactions, {d.span}</span></div>
        <div className={ln(2)}><Icon name="check" /><span dangerouslySetInnerHTML={{ __html: d.incomeLine }} /></div>
        <div className={ln(3)}><Icon name="check" /><span dangerouslySetInnerHTML={{ __html: d.billsLine }} /></div>
        <div className={ln(4)}><Icon name="check" /><span>Recognised <b>{d.known} merchants</b> you use</span></div>
        <div className={"ln" + (done ? "" : " wait") + (waitShown ? " show" : "")}>
          {done ? <><Icon name="check" /><span><b>All done.</b> Here{"\u2019"}s what we found.</span></> : <><span className="spin" /><span>Looking for patterns{"\u2026"}</span></>}
        </div>
      </div>
      {!live && <p className="demonote">This demo statement is pre-read so it runs instantly. Real statements take a little longer.</p>}
      <div className="row" style={{ marginTop: 8 }}><button className="link" onClick={() => { finishedRef.current = true; go("sorted"); }}>Skip ahead</button></div>
    </>
  );
}

function Sorted({ go, d }) {  // d.toReview/d.moreToReview come from the engine when the journey is engine-driven
  const [on, setOn] = useState(reducedMotion());
  useEffect(() => { const t = setTimeout(() => setOn(true), 250); return () => clearTimeout(t); }, []);
  const tot = d.merchants, toReview = d.toReview !== undefined ? d.toReview : d.quick + d.need;
  const w = (n) => (on ? (n / tot) * 100 + "%" : 0);
  return (
    <>
      <div className="kicker">Done reading</div>
      <h2>We{"\u2019"}ve organised your money</h2>
      <p className="hint" style={{ marginBottom: 0 }}>{d.merchants} merchants {"\u00B7"} {d.tx} transactions. You don{"\u2019"}t need to review everything.</p>
      <div className="bar"><i className="a" style={{ width: w(d.sorted) }} /><i className="b" style={{ width: w(d.quick) }} /><i className="c" style={{ width: w(d.need) }} /></div>
      <div className="legend">
        <div className="lg"><span className="sw" style={{ background: "var(--teal)" }} /><span className="n">{d.sorted}</span><span className="d"><b>Sorted for you</b><br />Nothing needed from you.</span></div>
        <div className="lg"><span className="sw" style={{ background: "rgba(46,102,89,.4)" }} /><span className="n">{d.quick}</span><span className="d"><b>Worth a quick look</b><br />We made a suggestion {"\u2014"} confirm or change it.</span></div>
        <div className="lg"><span className="sw" style={{ background: "var(--line-strong)" }} /><span className="n">{d.need}</span><span className="d"><b>Need your input</b><br />We couldn{"\u2019"}t tell what these are.</span></div>
      </div>
      <p className="muted" style={{ marginBottom: 28 }}>Together, the sorted ones already cover <b style={{ color: "var(--ink)" }}>{d.cov}% of your spending</b>.</p>
      <div className="actions"><button className="btn big" onClick={() => go("quick")}>{d.moreToReview > 0 ? "Review the " + toReview + " that matter most" : "Review the " + toReview + " that need you"}</button><button className="link" onClick={() => go("payoff")}>Skip to my picture {"\u2192"}</button></div>
      <p className="fine" style={{ marginTop: 16 }}>You can come back to the rest anytime.</p>
    </>
  );
}

/** The card for a merchant with transactions that are not fully categorised: only the missing fields, what is already known filled in. */
const FIELD_ORDER = ["category", "subCategory", "group", "frequencyClass", "frequency", "control", "purpose", "linkedAccountId"];
const FIELD_LABEL = { category: "What kind of money is this?", group: "Which group does it belong to?", frequencyClass: "How often does it happen?", frequency: "Repeats every", control: "Can you cut it?", purpose: "Personal or business?", linkedAccountId: "Which account is this for?" };
const emptyVal = (v) => v === null || v === undefined || v === "";
function FieldsCard({ c, onSave, onSkip }) {
  const [vals, setVals] = useState({});
  const [adding, setAdding] = useState(false), [draft, setDraft] = useState("");
  const sim = { ...c.base, ...vals };
  const need = c.spec.missing(sim);
  const shown = FIELD_ORDER.filter((f) => need.includes(f) || (c.missingNow.includes(f) && !emptyVal(sim[f])) || !emptyVal(vals[f]));
  const pick = (f, v) => setVals((cur) => {
    const next = { ...cur, [f]: v };
    if (f === "category") { next.subCategory = null; next.linkedAccountId = null; next.group = null; }
    if (f === "subCategory") next.linkedAccountId = null;
    if (f === "frequencyClass") { next.frequency = null; next.control = null; }
    return next;
  });
  const addGroup = () => { const name = draft.trim(); if (!name) return; pick("group", /^other$/i.test(name) ? "Others" : name); setAdding(false); setDraft(""); };
  const canSave = need.filter((f) => f !== "linkedAccountId").length === 0;
  return (
    <>
      {c.offer && <div className="fine" data-testid="offer-note" style={{ margin: "0 0 12px" }}>You added {c.offer.accountName}. Is this payment from it?</div>}
      {shown.map((f) => {
        let opts = c.spec.options(f, sim);
        if (f === "group" && !emptyVal(sim.group) && !opts.some((o) => o.value === sim.group)) opts = [...opts, { value: sim.group, label: sim.group }]; // a group made just now
        if (f === "group" && c.remarkHint) { const sg = c.remarkHint.group; opts = [{ value: sg, label: sg, suggested: true }, ...opts.filter((o) => o.value !== sg)]; } // what the person's remark points to: offered first, never chosen for them
        if (f === "linkedAccountId") opts = [...opts, { value: "__none__", label: c.offer ? "Not this account" : "It\u2019s an account I haven\u2019t added yet" }];
        const label = f === "subCategory" ? (sim.category === "Expense" ? "Household or personal?" : "Which kind?") : FIELD_LABEL[f];
        return (
          <div key={f} style={{ marginBottom: 14 }} data-field={f}>
            <div className="ask" style={{ fontSize: 15, marginBottom: 8 }}>{label}</div>
            {opts.length ? (
              <div className="chips">{opts.map((o) => <button key={o.value} className={"chip" + (sim[f] === o.value ? " sel" : "")} aria-pressed={sim[f] === o.value} data-suggested={o.suggested ? "true" : undefined} onClick={() => pick(f, o.value)}>{o.label}{f === "group" && c.suggestedGroup === o.value && sim[f] !== o.value ? " \u00B7 suggested" : ""}</button>)}
                {f === "group" && <button className="chip" data-testid="new-group" onClick={() => setAdding(true)}>New group{"\u2026"}</button>}</div>
            ) : <div className="fine" style={{ marginTop: 0 }}>No options yet.</div>}
            {f === "linkedAccountId" && sim.linkedAccountId === "__none__" && !c.offer && (
              <div style={{ marginTop: 10 }}>
                <div className="fine" style={{ margin: "0 0 6px" }}>What is the account called? We{"\u2019"}ll offer to link these when you add it.</div>
                <input data-testid="pending-account-name" value={vals.pendingAccountName !== undefined ? vals.pendingAccountName : c.name} onChange={(e) => pick("pendingAccountName", e.target.value)} style={{ width: "100%", boxSizing: "border-box", padding: "8px 10px", borderRadius: 6, border: "1px solid var(--line)", font: "inherit" }} />
              </div>
            )}
            {f === "group" && adding && (
              <div style={{ display: "flex", gap: 8, marginTop: 10 }}>
                <input data-testid="new-group-input" autoFocus value={draft} onChange={(e) => setDraft(e.target.value)} onKeyDown={(e) => e.key === "Enter" && addGroup()} placeholder="e.g. Eating out" style={{ flex: 1, padding: "8px 10px", borderRadius: 6, border: "1px solid var(--line)", font: "inherit" }} />
                <button className="btn ghost" onClick={addGroup}>Add</button>
              </div>
            )}
          </div>
        );
      })}
      <div className="qbtns" style={{ marginTop: 18 }}>
        <button className="btn teal" disabled={!canSave} onClick={() => onSave(sim)}>Save</button>
        <button className="link" onClick={onSkip}>Not sure</button>
      </div>
    </>
  );
}

function Quick({ go, onToast, cards, onAnswer, onDone, onBack, onSeeMerchant }) {
  const finish = onDone || (() => go("payoff")); // onboarding goes on to the payoff; the Home deck just closes
  const [QUICK] = useState(() => cards || QUICK_SCRIPT); // the deck is fixed when the cards open; answers must not reshuffle it
  const [i, setI] = useState(0);
  const [exiting, setExiting] = useState(false);
  const [changing, setChanging] = useState(false);
  const [own, setOwn] = useState("");
  const total = QUICK.length, c = QUICK[i];
  const advance = (msg, choice) => {
    if (exiting) return;
    if (choice && onAnswer) onAnswer(c, choice);
    onToast(msg); setExiting(true);
    setTimeout(() => {
      if (i + 1 >= total) { finish(); return; }
      setI(i + 1); setExiting(false); setChanging(false); setOwn("");
    }, 300);
  };
  return (
    <>
      <button className="back" onClick={() => (onBack ? onBack() : go("sorted"))}>{"\u2190"} Back</button>
      <div className="qcount"><span>{i + 1} of {total}</span><span className="pips">{QUICK.map((_, k) => <i key={k} className={k <= i ? "on" : ""} />)}</span></div>
      <div className="stack">
        <div className={"qcard" + (exiting ? " exit" : "")} key={i}>
          <div className="mname">{c.name}</div><div className="mmeta">{c.meta}{c.remarkCard && c.payees > 1 ? " \u00B7 " + c.payees + " different payees" : ""}</div>
          {c.remarks && c.remarks.length > 0 && (
            <div data-testid="card-remarks" style={{ margin: "-6px 0 14px", fontSize: 13, lineHeight: 1.5 }}>
              {c.remarks.slice(0, 3).map((r) => <div key={r.text}><span style={{ color: "var(--ink-soft)" }}>Remark:</span> <b>{r.text}</b>{r.count > 1 && <span style={{ color: "var(--ink-soft)" }}> {"\u00D7"}{r.count}</span>}</div>)}
              {c.remarks.length > 3 && <div style={{ color: "var(--ink-soft)" }}>+{c.remarks.length - 3} more remarks</div>}
              {c.remarkHint && <div data-testid="remark-hint" style={{ color: "var(--teal)" }}>The remark points to <b>{c.remarkHint.group}</b>{c.remarkHint.also && c.remarkHint.also.length > 0 ? " (also mentions " + c.remarkHint.also.join(", ") + ")" : ""}. It is offered first among the groups \u2014 tap it to confirm, or choose another.</div>}
            </div>
          )}
          {c.samples && c.samples.length > 0 && (
            <div data-testid="card-samples" style={{ margin: "-10px 0 20px", fontSize: 13, lineHeight: 1.45, color: "var(--ink-soft)" }}>
              {c.samples.map((x, k) => (
                <div key={x.id || k} style={{ display: "flex", gap: 10, justifyContent: "space-between", padding: "3px 0", borderTop: k ? "1px dashed var(--line)" : "none" }}>
                  <span style={{ minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{x.date} {"\u00B7"} {x.text}</span>
                  <b style={{ fontFamily: "'IBM Plex Mono',monospace", color: x.amount < 0 ? "var(--ink)" : "var(--teal)", whiteSpace: "nowrap" }}>{x.signed}</b>
                </div>
              ))}
              {onSeeMerchant && <button className="link" style={{ marginTop: 4 }} onClick={() => onSeeMerchant(c)}>{c.more > 0 ? "See all " + (c.samples.length + c.more) + " in Review" : "See in Review"} {"\u2192"}</button>}
            </div>
          )}
          {c.spec ? (
            <FieldsCard c={c} onSave={(sim) => advance("Saved: " + c.name + ". It will follow the same rule next time.", sim)} onSkip={() => advance("Skipped \u2014 we\u2019ll ask again later.")} />
          ) : c.guess ? (
            <>
              <div className="guess">Looks like <b>{c.guess}</b> {"\u00B7"} {c.tag}{c.conf === "Medium" && <><br /><span style={{ color: "var(--ink-soft)", fontSize: 12.5 }}>The amount varies, so we{"\u2019"}re still learning this one.</span></>}</div>
              <div className="qbtns">
                <button className="btn teal" onClick={() => advance("Remembered: " + c.name + " \u2192 " + c.guess + ". Next time it\u2019s sorted automatically.", c.guess)}>Looks right</button>
                <button className="btn ghost" onClick={() => setChanging(true)}>Change</button>
                <button className="link" onClick={() => advance("Skipped \u2014 we\u2019ll ask again later.")}>Not sure</button>
              </div>
              {changing && <div className="chips" style={{ marginTop: 16 }}>{CHANGE.map((x) => <button key={x} className="chip" onClick={() => advance("Got it: " + c.name + " \u2192 " + x + ".", x)}>{x}</button>)}</div>}
            </>
          ) : (
            <>
              <div className="ask">{c.ask || "What is this?"}</div>
              <div className="chips">{c.choices.map((x) => <button key={x} className="chip" onClick={() => advance("Got it: " + c.name + " \u2192 " + x + ".", x)}>{x}</button>)}</div>
              {c.customGroupBase && (
                <div className="row" style={{ marginTop: 12, gap: 8 }}>
                  <input type="text" aria-label="Your own group" placeholder="None fit? Name your own (e.g. Medical)" value={own} maxLength={40}
                    onChange={(e) => setOwn(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && own.trim()) advance("Got it: " + c.name + " \u2192 " + own.trim() + ".", own.trim()); }}
                    style={{ flex: 1, padding: "9px 12px", borderRadius: 10, border: "1px solid var(--line, #ddd)", font: "inherit" }} />
                  <button className="btn teal" disabled={!own.trim()} onClick={() => advance("Got it: " + c.name + " \u2192 " + own.trim() + ".", own.trim())}>Add</button>
                </div>
              )}
              <div className="row" style={{ marginTop: 14 }}><button className="link" onClick={() => advance("Skipped \u2014 we\u2019ll ask again later.")}>Not sure</button></div>
            </>
          )}
        </div>
      </div>
      {cards && <p className="fine" style={{ marginTop: 18 }}><button className="link" onClick={finish}>Finish later {"\u2014"} these wait for you on Home</button></p>}
    </>
  );
}

/** The by-merchant review deck as a full-screen layer, opened from Home. Same cards, same component as onboarding (backlog #79). */
export function ReviewDeck({ cards, onAnswer, onClose, onSeeAll, onSeeMerchant }) {
  const [toast, setToast] = useState("");
  const timer = useRef(null);
  const showToast = (m) => { setToast(m); clearTimeout(timer.current); timer.current = setTimeout(() => setToast(""), 2400); };
  useEffect(() => () => clearTimeout(timer.current), []);
  return (
    <div className="onb-root" style={{ position: "fixed", inset: 0, zIndex: 60, overflowY: "auto" }}>
      <OnbStyle />
      <div className="wrap"><main className="stage entering"><Quick go={onClose} onToast={showToast} cards={cards} onAnswer={onAnswer} onDone={onClose} onBack={onClose} onSeeMerchant={onSeeMerchant} />{onSeeAll && <p className="fine" style={{ marginTop: 6 }}><button className="link" onClick={onSeeAll}>Open the full Review table instead</button></p>}</main></div>
      <div className={"onb-toast" + (toast ? " show" : "")}>{toast}</div>
    </div>
  );
}

/* --- payoff + "what more history unlocks": the prototype's own template functions (journeyTemplates.generated.js,
   extracted verbatim), rendered as-is and driven by event delegation, exactly as the prototype binds them. --- */
const inr0 = (n) => "\u20B9" + Math.round(n).toLocaleString("en-IN");
function countUp(el, to, ms, fmt) {
  if (!el) return;
  if (reducedMotion()) { el.textContent = fmt(to); return; }
  let start = null;
  const step = (ts) => { if (!start) start = ts; const p = Math.min(1, (ts - start) / ms); el.textContent = fmt(to * (1 - Math.pow(1 - p, 3))); if (p < 1) requestAnimationFrame(step); };
  requestAnimationFrame(step);
}
function drawPath(root) {
  const fp = root && root.querySelector(".fpath");
  if (!fp || reducedMotion() || !fp.getTotalLength) return;
  const len = fp.getTotalLength();
  fp.style.strokeDasharray = len; fp.style.strokeDashoffset = len; fp.getBoundingClientRect();
  fp.style.transition = "stroke-dashoffset 1.4s ease"; fp.style.strokeDashoffset = 0;
}

/** Own-statement journey: a CSV or pasted statement may not carry today's balance, and the payoff cannot honestly show cash without it. */
function BalanceAsk({ go, asOf, onSetBalance }) {
  const [v, setV] = useState("");
  const n = Number(String(v).replace(/[^0-9.]/g, ""));
  return (
    <>
      <div className="kicker">Your money</div>
      <h2>One number I can{"\u2019"}t read</h2>
      <p className="hint">Your statement doesn{"\u2019"}t tell me your balance. What was the closing balance on {asOf}? It stays on this device, and it lets me show your cash and where it is headed.</p>
      <div className="card">
        <div className="lbl">Closing balance (₹)</div>
        <div className="row" style={{ gap: 10 }}>
          <input type="text" inputMode="decimal" aria-label="Closing balance" placeholder="e.g. 186000" value={v} onChange={(e) => setV(e.target.value)}
            onKeyDown={(e) => { if (e.key === "Enter" && n > 0) onSetBalance(n); }}
            style={{ flex: 1, padding: "10px 12px", borderRadius: 10, border: "1px solid var(--line, #ddd)", font: "inherit" }} />
          <button className="btn teal" disabled={!(n > 0)} onClick={() => onSetBalance(n)}>Use this balance</button>
        </div>
      </div>
      <div className="row" style={{ marginTop: 14 }}><button className="link" onClick={() => go("next")}>Skip for now {"\u2192"}</button></div>
    </>
  );
}

function Payoff({ go, demo, onBridge }) {
  const S = T.getS(); S.demo = demo;
  const [, setTick] = useState(0);
  const ref = useRef(null);
  const html = T.payoffHTML();
  const inner = useMemo(() => ({ __html: html }), [html]); // a fresh object each render makes React rewrite the markup (undoing the cash count-up)
  useEffect(() => {
    const cash = ref.current && ref.current.querySelector("#cash");
    if (S._drawn) { if (cash) cash.textContent = inr0(T.TODAY); } else countUp(cash, T.TODAY, 1200, inr0);
    S._drawn = true; drawPath(ref.current);
  }, [html]); // eslint-disable-line react-hooks/exhaustive-deps
  const onClick = (e) => {
    const b = e.target.closest("button"); if (!b) return;
    if (b.dataset.go === "next") go("next");
    else if (b.dataset.c) { S.cushion = b.dataset.c; setTick((x) => x + 1); }
    else if (b.id === "bridge1") onBridge();
  };
  return <div ref={ref} onClick={onClick} dangerouslySetInnerHTML={inner} />;
}

function Next({ demo, onFinish, onStartUpload, onBridge, onToast }) {
  const S = T.getS(); S.demo = demo;
  const ref = useRef(null);
  const [html] = useState(() => T.nextHTML()); // rendered once; later changes mutate #journey in place, as the prototype does
  const inner = useMemo(() => ({ __html: html }), [html]); // a fresh {__html} object each render makes React rewrite the markup and undo those in-place changes (a toast clearing re-renders the flow)
  useEffect(() => { drawPath(ref.current && ref.current.querySelector("#journey")); }, []);
  const setH = (h) => { S.h = h; const j = ref.current.querySelector("#journey"); j.innerHTML = T.journeyHTML(); drawPath(j); };
  const addMore = () => (demo ? onToast("In the real app this opens the upload screen.") : onStartUpload());
  const onClick = (e) => {
    const b = e.target.closest("button"); if (!b || !ref.current.contains(b)) return;
    if (b.classList.contains("lseg")) T.showStage(parseInt(b.getAttribute("data-i"), 10));
    else if (b.id === "stepbtn") setH(T.STEPS[T.STEPS.indexOf(S.h) + 1]);
    else if (b.id === "jump6") setH(6);
    else if (b.id === "resetH") setH(1);
    else if (b.parentNode.classList && b.parentNode.classList.contains("askchips")) { S.ans[b.parentNode.getAttribute("data-k")] = b.getAttribute("data-a"); setH(S.h); }
    else if (b.id === "addmonths" || b.id === "addacct") addMore();
    else if (b.id === "bridge2") onBridge();
  };
  return (
    <>
      <div ref={ref} onClick={onClick} dangerouslySetInnerHTML={inner} />
      <div className="dashbar"><span>You can add more anytime.</span>
        <button className="btn" onClick={() => onFinish({ demo, h: S.h, feeAns: T.ans("fee"), insAns: T.ans("ins") })}>Your dashboard is ready {"\u2192"}</button></div>
    </>
  );
}

/* ------------------------------------------------------------------ the flow */

export default function OnboardingFlow({
  demo = false, household, setHousehold, priority, setPriority, setHouseholdAnswered,
  onStartUpload, onTryDemo, onExitDemo, onFinish, journeySource, startAt,
  priorities, setPriorities, householdAnswered, intakeStatus, intakeControlRef, onPickFile, onGoHome, addFor,
}) {
  const h0 = (journeySource && journeySource.h) || 1; // a live (own-statement) journey reads the window that matches the months actually uploaded
  // Engine-driven journey (backlog #79): when a statement source is given, every figure and review card below is
  // computed from it by the engine; card answers are kept and fed back so a sorted merchant stays sorted.
  const [answers, setAnswers] = useState([]);
  const jr = useMemo(() => (journeySource ? buildJourney(journeySource.rows(), journeySource.engine, journeySource.historyEnd, answers, journeySource.live ? { h: journeySource.h, today: journeySource.today, accountName: journeySource.accountName } : null) : null), [journeySource, answers]);
  const hooks = useMemo(() => (jr ? jr.engineHooks(journeySource.forecast) : null), [jr, journeySource]); // Payoff / stepper figures from the engine
  T.setEngine(hooks);
  if (jr) JOURNEY_STEPS.forEach((h) => { if (T.DATA[h]) { T.DATA[h].quick = jr.data(h).toReview; T.DATA[h].need = 0; } }); // the template only sums quick+need (toReview)
  const FEE_CODE = { "Every 6 months": "6m", "Every year": "year", "One-off": "once", "Not sure": "unsure" };
  const onAnswer = (c, choice) => {
    if (c.repeat && journeySource && journeySource.live) { // a real statement: the answer sets that merchant's cadence itself
      T.getS().ans[/school/i.test(c.name) ? "fee" : "ins"] = FEE_CODE[choice] || "unsure";
      setAnswers((a) => [...a.filter((x) => x.key !== "repeat:" + c.key), { key: "repeat:" + c.key, label: choice, cadence: REPEAT_CADENCE[choice] || null }]);
      return;
    }
    if (c.repeat) { const k = /school/i.test(c.name) ? "fee" : "ins"; T.getS().ans[k] = FEE_CODE[choice] || "unsure"; }
    setAnswers((a) => [...a.filter((x) => x.key !== c.key), { key: c.key, label: choice, patch: patchForAnswer(c, choice) }]);
  };
  // "Start with my statement" from inside the demo exits the sandbox (a reload) and should land on Q1, as the
  // prototype's fresh()+goto('q1') does - the screen to start at survives the reload in sessionStorage.
  const [screen, setScreen] = useState(() => {
    if (demo) { T.fresh(); return "meet"; }
    if (addFor) return "statement"; // "Add another account" from Home: straight to choosing the statement
    if (startAt && journeySource) { T.fresh(); T.getS().h = journeySource.h; return startAt; }
    let at = null; try { at = window.sessionStorage.getItem("bw_start_at"); window.sessionStorage.removeItem("bw_start_at"); } catch (e) { /* storage unavailable */ }
    return at || "welcome";
  });
  // An own-statement journey that appears AFTER mount (the statement was read on the intake screen): start the templates at the months uploaded.
  useEffect(() => { if (journeySource && journeySource.live) { T.fresh(); T.getS().h = journeySource.h; } }, [journeySource && journeySource.live]); // eslint-disable-line react-hooks/exhaustive-deps
  const bridgeToReal = () => { try { window.sessionStorage.setItem("bw_start_at", "statement"); } catch (e) { /* storage unavailable */ } onExitDemo && onExitDemo(); };
  const [leaving, setLeaving] = useState(false);
  const [toast, setToast] = useState("");
  const toastTimer = useRef(null);
  const showToast = (m) => { setToast(m); clearTimeout(toastTimer.current); toastTimer.current = setTimeout(() => setToast(""), 2600); };
  useEffect(() => () => clearTimeout(toastTimer.current), []);

  // Same leave-then-enter transition the prototype's goto() uses (220ms), skipped for reduced motion.
  const go = (name) => {
    setLeaving(true);
    setTimeout(() => { setScreen(name); setLeaving(false); window.scrollTo && window.scrollTo(0, 0); }, reducedMotion() ? 0 : 220);
  };
  const d = jr ? jr.data(h0) : DEMO_DATA[1];

  let body = null;
  if (screen === "welcome") body = <Welcome go={go} onTryDemo={onTryDemo} onGoHome={onGoHome} />;
  else if (screen === "q1") body = <Q1 go={go} household={household} setHousehold={setHousehold} setHouseholdAnswered={setHouseholdAnswered} />;
  else if (screen === "q2") body = <Q2 go={go} priorities={priorities} setPriorities={setPriorities} />;
  else if (screen === "statement") body = <Statement go={go} onPickFile={onPickFile} onTryDemo={onTryDemo} why={addFor} onBack={addFor && onGoHome ? onGoHome : null} />;
  else if (screen === "intake") body = <Intake go={go} status={intakeStatus} controlRef={intakeControlRef} onPickFile={onPickFile} onToast={showToast} addMode={!!addFor} ready={!!(journeySource && journeySource.live)} household={household} setHousehold={setHousehold} householdAnswered={householdAnswered} setHouseholdAnswered={setHouseholdAnswered} priorities={priorities} setPriorities={setPriorities} />;
  else if (screen === "meet") body = <Meet go={go} />;
  else if (screen === "reading") body = <Reading go={go} d={d} live={!!(journeySource && journeySource.live)} accountName={journeySource && journeySource.accountName} />;
  else if (screen === "sorted") body = <Sorted go={go} d={d} />;
  else if (screen === "quick") body = <Quick go={go} onToast={showToast} cards={jr ? jr.cards(h0) : null} onAnswer={jr ? onAnswer : null} />;
  else if (screen === "payoff") body = journeySource && journeySource.live && !journeySource.balanceKnown ? <BalanceAsk go={go} asOf={journeySource.historyEnd} onSetBalance={journeySource.onSetBalance} /> : <Payoff go={go} demo={demo} onBridge={bridgeToReal} />;
  else if (screen === "next") body = <Next demo={demo} onFinish={(info) => onFinish({ ...info, answers })} onStartUpload={onStartUpload} onBridge={bridgeToReal} onToast={showToast} />;

  return (
    <div className="onb-root" style={screen === "next" ? { paddingBottom: 96 } : undefined}>
      <OnbStyle />
      {demo && <div className="demopill"><div><i /><span>Demo &middot; sample data, not yours</span><button onClick={onExitDemo}>Exit</button></div></div>}
      <div className={"wrap" + (screen === "next" ? " wide" : "")}>
        <main className={"stage " + (leaving ? "leaving" : "entering")} key={screen} aria-live="polite">{body}</main>
        {screen !== "welcome" && <div className="foot"><span className="l"><Icon name="lock" style={{ width: 13, height: 13 }} /><span>Saved only on this device</span></span></div>}
      </div>
      <div className={"onb-toast" + (toast ? " show" : "")}>{toast}</div>
    </div>
  );
}
