"""Extracts the prototype's .home-root CSS (the Ask panel, bar, chips, buttons...) VERBATIM, brace-aware, into
src/ask/askStyles.js - copied from the artifact, never retyped. The prototype's light :root variables are re-scoped
to .home-root so nothing leaks into the rest of the app."""
import sys, json
src = open(sys.argv[1]).read()
css = src[src.index("<style>")+7 : src.index("</style>")]
rules, depth, buf = [], 0, ""
for ch in css:
    buf += ch
    if ch == "{": depth += 1
    elif ch == "}":
        depth -= 1
        if depth == 0:
            rules.append(buf.strip()); buf = ""
keep = []
for r in rules:
    head = r.split("{")[0].strip()
    if head == ":root":
        keep.append(r.replace(":root", ".home-root", 1))
    elif head.startswith("@media") and "prefers-color-scheme" in head: continue
    elif head.startswith("@media") and ".home-root" in r: keep.append(r)
    elif head.startswith("@keyframes") and head.split()[1] in ("slidein",): keep.append(r)
    elif head.startswith(".home-root"): keep.append(r)
out = "\n".join(keep)
open(sys.argv[2], "w").write(
 "// GENERATED by tools/extract_home_css.py from journey-prototype-v1.html (29 Sep artifact). Do not hand-edit.\n"
 "export const HOME_CSS = " + json.dumps(out) + ";\n")
print(len(keep), "rules kept of", len(rules))
