"""Extracts the prototype's journey logic (payoff, 'what more history unlocks', stepper data) VERBATIM
into src/onboarding/journeyTemplates.generated.js - copied from the 29 Sep artifact, never retyped.
Refuses to run against any other version of the artifact (md5 pinned)."""
import sys, re, hashlib
src_path, out_path = sys.argv[1], sys.argv[2]
raw = open(src_path, encoding="utf-8").read()
assert hashlib.md5(raw.encode()).hexdigest() == "7e833cfd2f8c4c70ec4903a6efba7fe3", "not the 29 Sep artifact"
# the onboarding script block is the SECOND IIFE (the first is Home's)
second = raw[raw.index("var IC = {"):]
def between(a, b, start=0, text=None):
    t = text if text is not None else second
    i = t.index(a, start); j = t.index(b, i + len(a)); return t[i:j], j
head_icons, _ = between("var IC = {", "function later(")                 # IC table + icon() + fmtINR/fmtK + $ helpers
blockA, _ = between("var S;", "var SCREENS = {};")                       # state, DATA, QUICK.., PTS.., ans, FC
chart, _ = between("function chartSVG(h){", "function drawPath(root)")
payofftext, _ = between("function payoffText(h){", "SCREENS.payoff = {")
pay_body = between("SCREENS.payoff = { html:function(){", "},\n init:function(){")[0].split("html:function(){",1)[1]
blockC, _ = between("var STAGES = [", "SCREENS.next = {")
next_body = between("SCREENS.next = { html:function(){", "},\n init:function(){")[0].split("html:function(){",1)[1]
# drop the DOM-touching helpers we do not use from the head (later/timers/toast/countUp are re-done in React)
head_icons = head_icons.rstrip()
out = f"""// GENERATED by tools/extract_journey.py from journey-prototype-v1.html (29 Sep artifact, md5 pinned). Do not hand-edit.
/* eslint-disable */
{"" if "var reduced" in head_icons else "var reduced = false;"}
{head_icons}
{blockA}
{chart}
{payofftext}
function payoffHTML(){{{pay_body}}}
{blockC}
function nextHTML(){{{next_body}}}
export function getS(){{ return S; }}
export {{ fresh, D, toReview, FC, TODAY, LOWDATE, CUSH, DATA, QUICK, payoffText, payoffHTML, nextHTML, journeyHTML, showStage, ans, STAGEOF, STEPS, MN_DUMMY }};
"""
out = out.replace(", MN_DUMMY", "")

# ---------------------------------------------------------------------------------------------------------------
# ENGINE HOOKS (backlog #81 / #82). The prototype's text above is verbatim; the few places where it held a SCRIPTED
# figure (bill list, snapshot, normal month, forecast points, lowest point, cushion options, stepper notes, festive
# claim, "richer" prompts) now ask an engine object first (`ENG`, set from the app with setEngine) and fall back to the
# prototype's own value when there is none (the real, non-demo journey). Every replacement is asserted, so a changed
# artifact fails loudly instead of silently dropping a hook.
def patch(text, old, new, count=1):
    n = text.count(old)
    assert n == count, ("patch target", old[:70], "found", n, "expected", count)
    return text.replace(old, new)
out = patch(out, "var TODAY = 186000, LOWDATE = '30 Nov';",
  "var TODAY = 186000, LOWDATE = '30 Nov';\n"
  "var ENG = null;\n"
  "function LD(){ return ENG && ENG.lowdate ? ENG.lowdate(S.h, ans('fee'), ans('ins')) : LOWDATE; }\n"
  "function SN(k, d){ return ENG && ENG.snapshot ? ENG.snapshot()[k] : d; }\n"
  "function shortINR(n){ return n>=100000 ? (n/100000).toFixed(2).replace(/\\.?0+$/,'')+'L' : Math.round(n/1000)+'K'; }")
out = patch(out, "function FC(h){\n", "function FC(h){\n  if(ENG && ENG.fc) return ENG.fc(h, ans('fee'), ans('ins'));\n")
out = out.replace("+LOWDATE+", "+LD()+"); assert "+LD()+" in out
out = patch(out, "[['1','1 month of spending \\u00B7 \\u20B978K'],['3','3 months \\u00B7 \\u20B92.34L'],['6','6 months \\u00B7 \\u20B94.68L']]",
  "(ENG && ENG.cush ? [['1','1 month of spending \\u00B7 '+shortINR(CUSH['1'])],['3','3 months \\u00B7 '+shortINR(CUSH['3'])],['6','6 months \\u00B7 '+shortINR(CUSH['6'])]] : [['1','1 month of spending \\u00B7 \\u20B978K'],['3','3 months \\u00B7 \\u20B92.34L'],['6','6 months \\u00B7 \\u20B94.68L']])")
# first-look snapshot
out = patch(out, "'<div><div class=\"v\">\\u20B91,10,000</div><div class=\"l\">Income</div></div>'+", "'<div><div class=\"v\">'+SN('income','\\u20B91,10,000')+'</div><div class=\"l\">Income</div></div>'+")
out = patch(out, "'<div><div class=\"v\">\\u20B996,000</div><div class=\"l\">Spending</div></div>'+", "'<div><div class=\"v\">'+SN('spending','\\u20B996,000')+'</div><div class=\"l\">'+SN('spendLabel','Spending')+'</div></div>'+")
out = patch(out, "'<div><div class=\"v\">\\u20B914,000</div><div class=\"l\">Net cash generated</div></div>'+", "'<div><div class=\"v\">'+SN('net','\\u20B914,000')+'</div><div class=\"l\">'+SN('netLabel','Net cash generated')+'</div></div>'+")
out = patch(out, "'<div><div class=\"v\">68</div><div class=\"l\">Transactions</div></div>'+", "'<div><div class=\"v\">'+SN('transactions','68')+'</div><div class=\"l\">Transactions</div></div>'+")
out = patch(out, "'<div><div class=\"v\">5</div><div class=\"l\">Recurring-looking merchants</div></div>'+", "'<div><div class=\"v\">'+SN('lookRecurring','5')+'</div><div class=\"l\">Recurring-looking merchants</div></div>'+")
out = patch(out, "'<div><div class=\"v\">\\u20B931,000</div><div class=\"l\">Discretionary spending</div></div>'+", "'<div><div class=\"v\">'+SN('discretionary','\\u20B931,000')+'</div><div class=\"l\">Discretionary spending</div></div>'+")
# bills that repeat
out = patch(out, "var out='', seenOnce=(h<2), list=seenOnce?BILLS.slice(0,5):BILLS;", "var out='', seenOnce=(h<2), list=(ENG&&ENG.bills)?ENG.bills(h):(seenOnce?BILLS.slice(0,5):BILLS);")
out = patch(out, "var isNew=(S.demo && h===2 && i>=5);", "var isNew=(ENG&&ENG.bills)?!!b[3]:(S.demo && h===2 && i>=5);")
out = patch(out, "These five look like monthly bills", "These '+(ENG&&ENG.bills?list.length:'five')+' look like monthly bills")
# a normal month (real figures: it can be a deficit)
out = patch(out, "<div class=\"snap three\"><div><div class=\"v\">\\u20B91,10,000</div><div class=\"l\">In</div></div><div><div class=\"v\">\\u20B996,000</div><div class=\"l\">Out</div></div><div><div class=\"v\">\\u20B914,000</div><div class=\"l\">Left over</div></div></div></div>",
  "<div class=\"snap three\"><div><div class=\"v\">'+NM(h,'inn','\\u20B91,10,000')+'</div><div class=\"l\">In</div></div><div><div class=\"v\">'+NM(h,'out','\\u20B996,000')+'</div><div class=\"l\">Out</div></div><div><div class=\"v\">'+NM(h,'net','\\u20B914,000')+'</div><div class=\"l\">'+NM(h,'label','Left over')+'</div></div></div></div>")
out = patch(out, "function SN(k, d)", "function NM(h, k, d){ return ENG && ENG.normal ? ENG.normal(h)[k] : d; }\nfunction SN(k, d)")
# stepper notes, seasons, richer prompts
out = patch(out, "<div class=\"k\">New with this step</div>'+NEWNOTE[h]+'", "<div class=\"k\">New with this step</div>'+((ENG&&ENG.note&&ENG.note(h))||NEWNOTE[h])+'")
old_season = "Spending ran about <b>22% higher</b> in October\\u2013November last year \\u2014 the festive season."
out = patch(out, old_season, "'+(ENG&&ENG.season?ENG.season():'" + old_season + "')+'")
out = patch(out, "var rich = RICH[S.demo?'demo':'real'];", "var rich = (ENG && ENG.rich && S.demo) ? ENG.rich() : RICH[S.demo?'demo':'real'];")
out = patch(out, "export function getS(){ return S; }", "export function getS(){ return S; }\nexport function setEngine(e){ ENG = e; if(e && e.cush) CUSH = e.cush; }")

# ---------------------------------------------------------------------------------------------------------------
# LIVE (own-statement) HOOKS (backlog #72). The same screens, driven by the person's own statement: cash today, the
# "as of" caption, the chart's date labels, the "found" sentences and the once-or-twice-a-year section come from ENG
# when it provides them (live journey only); the demo keeps the prototype's text.
out = patch(out, "<small>as of 28 Sep \\u00B7 Sample Bank savings</small>", "<small>'+(ENG&&ENG.cashNote?ENG.cashNote():'as of 28 Sep \\u00B7 Sample Bank savings')+'</small>")
out = patch(out, "[['Today',0,'start'],['1 Dec',64,'middle'],['27 Dec',90,'end']]", "(ENG&&ENG.axis?ENG.axis():[['Today',0,'start'],['1 Dec',64,'middle'],['27 Dec',90,'end']])")
out = patch(out, "var MAXV=Math.max(330, c*1.1);", "var MAXV=Math.max(330, c*1.1, pts.reduce(function(m,p){ return Math.max(m,p[1]); }, 0)*1.15);")
out = patch(out, "function foundText(h){\n", "function foundText(h){\n  if(ENG && ENG.found && !S.demo) return ENG.found(h);\n")
out = patch(out, "  if(h>=12){\n    out += '<div class=\"sec\"><div class=\"sh\">Bills that come once or twice a year</div>'+\n      '<div class=\"bill\"><div><b>School fee</b>",
  "  if(!S.demo && ENG && ENG.periodic && h>=6){ out += ENG.periodic(h); }\n  else if(h>=12){\n    out += '<div class=\"sec\"><div class=\"sh\">Bills that come once or twice a year</div>'+\n      '<div class=\"bill\"><div><b>School fee</b>")
out = patch(out, "var rich = (ENG && ENG.rich && S.demo) ? ENG.rich() : RICH[S.demo?'demo':'real'];", "var rich = (ENG && ENG.rich && (S.demo || ENG.live)) ? ENG.rich() : RICH[S.demo?'demo':'real'];")
out = patch(out, "export function setEngine(e){ ENG = e; if(e && e.cush) CUSH = e.cush; }", "export function setEngine(e){ ENG = e; if(e && e.cush) CUSH = e.cush; TODAY = (e && e.today != null) ? e.today : 186000; }")
open(out_path, "w", encoding="utf-8").write(out)
print("generated", len(out), "bytes")
