"""Extracts the prototype's .onb-root CSS VERBATIM (brace-aware, so multi-line rules are kept whole)
into src/onboarding/onbStyles.js - copied from the artifact, never retyped."""
import re, sys, json
src = open(sys.argv[1]).read()
css = src[src.index("<style>")+7 : src.index("</style>")]
rules, depth, buf = [], 0, ""
for ch in css:
    buf += ch
    if ch == "{": depth += 1
    elif ch == "}":
        depth -= 1
        if depth == 0:
            rules.append(buf.strip()); buf = ""
keep = []
for r in rules:
    head = r.split("{")[0].strip()
    if head.startswith("@media") and "prefers-color-scheme" in head: continue   # app has its own theme toggle
    if head.startswith("@media") and ".onb-root" in r: keep.append(r)
    elif head.startswith("@keyframes") and head.split()[1] in ("rise","spin","cardin","cardout"): keep.append(r)
    elif head.startswith(".onb-root") : keep.append(r)
    elif head.startswith(".toast"): keep.append(r.replace(".toast", ".onb-toast"))
out = "\n".join(keep)
open(sys.argv[2], "w").write(
 "// GENERATED by tools/extract_onb_css.py from journey-prototype-v1.html (29 Sep artifact). Do not hand-edit.\n"
 "export const ONB_CSS = " + json.dumps(out) + ";\n")
print(len(keep), "rules kept of", len(rules))
